"""Loader for the generated lifter-chain tables.

Everything else in this package is generated by
``scripts/generate_lifter_chains.py`` (``cluster_*.py``, per-home modules,
``_index.py``); this loader is the only hand-written file.  Per-home modules
import lazily so a world pays only for its own home body.
"""
from __future__ import annotations

import importlib
from typing import Optional, TYPE_CHECKING

from ...lifter_binding import (
    AscentConstraints, BoundLadder, BoundLifterTable, BoundRung,
    LifterHint, OFFSET_TO_NAME,
)

if TYPE_CHECKING:
    from ...bodies import BodyName


def n_profiles(home: "BodyName", pack_key: tuple[str, ...]) -> int:
    """Number of chains available for (home, pack set); 0 when the table has
    no data for the combination (loader then returns None => raw physics)."""
    try:
        from . import _index
    except ImportError:
        return 0
    cluster = _index.HOME_CLUSTER.get(home.value)
    if cluster is None:
        return 0
    cmod = importlib.import_module(f".cluster_{cluster}", __package__)
    return len(cmod.CHAINS.get(tuple(pack_key), ()))


def load_lifter_table(home: "BodyName", pack_key: tuple[str, ...],
                      profile_id: int,
                      phys_profile: str) -> Optional[BoundLifterTable]:
    """Materialize one seed's bound lifter table, or None when the data
    doesn't cover (home, pack set, physics profile) — callers treat None as
    "use raw physics everywhere"."""
    try:
        from . import _index
    except ImportError:
        return None
    cluster = _index.HOME_CLUSTER.get(home.value)
    if cluster is None:
        return None
    cmod = importlib.import_module(f".cluster_{cluster}", __package__)
    hmod = importlib.import_module(f".{home.value.lower()}", __package__)
    pack_key = tuple(pack_key)
    chains = cmod.CHAINS.get(pack_key)
    rows_by_phys = hmod.LADDER_ROWS.get(pack_key, {})
    if not chains or phys_profile not in rows_by_phys:
        return None
    if not (0 <= profile_id < len(chains)):
        return None

    ci = hmod.CONSTRAINTS[pack_key][phys_profile]
    meta = hmod.LADDER_META[pack_key][phys_profile]
    rows = hmod.LADDER_ROWS[pack_key][phys_profile][profile_id]
    constraints = AscentConstraints(
        in_atmosphere=bool(ci[0]), min_twr_liftoff=ci[1],
        requires_throttleable=bool(ci[2]), srb_needs_rcs=bool(ci[3]),
        needs_heat_shield=bool(ci[4]), pad_altitude_m=ci[5],
    )
    hints = tuple(LifterHint(split=h[0], stages=h[1])
                  for h in hmod.HINTS[pack_key])
    ladders = tuple(
        BoundLadder(
            dv=dv, ceiling_t=ceiling, constraints=constraints,
            rungs=tuple(BoundRung(threshold_t=thresholds[r[0]],
                                  prefix_len=r[1],
                                  launch_mass=r[2], hint=hints[r[3]])
                        for r in rungs),
        ) for (dv, ceiling, thresholds), rungs in zip(meta, rows))
    chain = tuple(OFFSET_TO_NAME[o] for o in chains[profile_id])
    return BoundLifterTable(
        home=home, profile_id=profile_id, chain=chain,
        ladders={phys_profile: ladders}, phys_profile=phys_profile,
    )
