"""Generated by scripts/generate_lifter_chains.py; do not hand-edit."""

DIGEST = 'b4355fab4f43d34ca98a825c0f6119f205eeba77cb8b4b84c678b0f675a4f1e2'
HOME_CLUSTER = {
    'Bop': 'vac_micro',
    'Dres': 'vac_low',
    'Duna': 'atmo_thin',
    'Eeloo': 'vac_low',
    'Eve': 'eve',
    'Gilly': 'vac_micro',
    'Ike': 'vac_low',
    'Kerbin': 'atmo_thick',
    'Laythe': 'atmo_thick',
    'Minmus': 'vac_micro',
    'Moho': 'vac_low',
    'Mun': 'vac_low',
    'Pol': 'vac_micro',
    'Tylo': 'tylo',
    'Vall': 'vac_low',
}
