"""Generated by scripts/generate_lifter_chains.py; do not hand-edit."""

DIGEST = '831e041eedc6de2ecf1614826278e5204f26d077e72c42bd67e15563ed94d3ad'
HOME_CLUSTER = {
    'Bop': 'vac_micro',
    'Dres': 'vac_low',
    'Duna': 'atmo_thin',
    'Eeloo': 'vac_low',
    'Eve': 'eve',
    'Gilly': 'vac_micro',
    'Ike': 'vac_low',
    'Kerbin': 'atmo_thick',
    'Laythe': 'atmo_thick',
    'Minmus': 'vac_micro',
    'Moho': 'vac_low',
    'Mun': 'vac_low',
    'Pol': 'vac_micro',
    'Tylo': 'tylo',
    'Vall': 'vac_low',
}
