"""Generated by scripts/generate_lifter_chains.py; do not hand-edit."""

DIGEST = '1fd02e936c55662bff1bff80ee43aaaf18793ea513f7db833a8e55f4f9814799'
HOME_CLUSTER = {
    'Bop': 'vac_micro',
    'Dres': 'vac_low',
    'Duna': 'atmo_thin',
    'Eeloo': 'vac_low',
    'Eve': 'eve',
    'Gilly': 'vac_micro',
    'Ike': 'vac_low',
    'Kerbin': 'atmo_thick',
    'Laythe': 'atmo_thick',
    'Minmus': 'vac_micro',
    'Moho': 'vac_low',
    'Mun': 'vac_low',
    'Pol': 'vac_micro',
    'Tylo': 'tylo',
    'Vall': 'vac_low',
}
