"""Static model-infeasible-missions table — checked in,
regenerated by ``worlds/ksp1/scripts/generate_feasibility.py``.

For each (difficulty, home), lists the ``(target_body, mission_type)``
pairs whose mission the dv model cannot verify even given a maxed-out
parts kit; those missions fall back to the "all-parts collected" proxy
at goal time.  The world reads the pairs directly into
``unachievable_missions`` — no per-name parsing — and expands them back
over ``MISSION_LOCATIONS`` for the name-keyed consumers.

Keyed by which capability-relevant part packs are enabled.
``MODEL_INFEASIBLE_BASE`` is the default config (``BASE_RELEVANT_PACKS``);
``MODEL_INFEASIBLE_DELTAS`` holds signed (added, removed) diffs vs base
for any other capability-relevant pack set.  An empty deltas dict means
no pack changes what capability can represent.  The world resolves
base ⊕ delta for the seed's enabled capability-relevant packs.

This file is generated; do not hand-edit.  Re-run the script whenever
the dv model, mission graph, or part database changes.
"""
from __future__ import annotations

from worlds.ksp1.bodies import BodyName, EdgeType, MissionType


BASE_RELEVANT_PACKS: tuple[str, ...] = ('MakingHistory', 'Stock')


MODEL_INFEASIBLE_BASE: dict[str, dict[BodyName, frozenset[tuple[BodyName, MissionType]]]] = {
    'generous': {
        BodyName.BOP: frozenset(),
        BodyName.DRES: frozenset(),
        BodyName.DUNA: frozenset(),
        BodyName.EELOO: frozenset(),
        BodyName.EVE: frozenset({(BodyName.BOP, MissionType.RETURN), (BodyName.BOP, MissionType.SAMPLE_RETURN), (BodyName.EELOO, MissionType.SAMPLE_RETURN), (BodyName.LAYTHE, MissionType.RETURN), (BodyName.LAYTHE, MissionType.SAMPLE_RETURN), (BodyName.MOHO, MissionType.SAMPLE_RETURN), (BodyName.POL, MissionType.SAMPLE_RETURN), (BodyName.TYLO, MissionType.RETURN), (BodyName.TYLO, MissionType.SAMPLE_RETURN), (BodyName.VALL, MissionType.SAMPLE_RETURN)}),
        BodyName.GILLY: frozenset(),
        BodyName.IKE: frozenset(),
        BodyName.KERBIN: frozenset(),
        BodyName.LAYTHE: frozenset({(BodyName.EVE, MissionType.SAMPLE_RETURN)}),
        BodyName.MINMUS: frozenset(),
        BodyName.MOHO: frozenset(),
        BodyName.MUN: frozenset(),
        BodyName.POL: frozenset(),
        BodyName.TYLO: frozenset(),
        BodyName.VALL: frozenset(),
    },
    'comfortable': {
        BodyName.BOP: frozenset(),
        BodyName.DRES: frozenset(),
        BodyName.DUNA: frozenset(),
        BodyName.EELOO: frozenset(),
        BodyName.EVE: frozenset(),
        BodyName.GILLY: frozenset(),
        BodyName.IKE: frozenset(),
        BodyName.KERBIN: frozenset(),
        BodyName.LAYTHE: frozenset(),
        BodyName.MINMUS: frozenset(),
        BodyName.MOHO: frozenset(),
        BodyName.MUN: frozenset(),
        BodyName.POL: frozenset(),
        BodyName.TYLO: frozenset(),
        BodyName.VALL: frozenset(),
    },
    'small': {
        BodyName.BOP: frozenset(),
        BodyName.DRES: frozenset(),
        BodyName.DUNA: frozenset(),
        BodyName.EELOO: frozenset(),
        BodyName.EVE: frozenset(),
        BodyName.GILLY: frozenset(),
        BodyName.IKE: frozenset(),
        BodyName.KERBIN: frozenset(),
        BodyName.LAYTHE: frozenset(),
        BodyName.MINMUS: frozenset(),
        BodyName.MOHO: frozenset(),
        BodyName.MUN: frozenset(),
        BodyName.POL: frozenset(),
        BodyName.TYLO: frozenset(),
        BodyName.VALL: frozenset(),
    },
    'zero': {
        BodyName.BOP: frozenset(),
        BodyName.DRES: frozenset(),
        BodyName.DUNA: frozenset(),
        BodyName.EELOO: frozenset(),
        BodyName.EVE: frozenset(),
        BodyName.GILLY: frozenset(),
        BodyName.IKE: frozenset(),
        BodyName.KERBIN: frozenset(),
        BodyName.LAYTHE: frozenset(),
        BodyName.MINMUS: frozenset(),
        BodyName.MOHO: frozenset(),
        BodyName.MUN: frozenset(),
        BodyName.POL: frozenset(),
        BodyName.TYLO: frozenset(),
        BodyName.VALL: frozenset(),
    },
}


# Signed (added, removed) diffs vs MODEL_INFEASIBLE_BASE, keyed by the
# seed's sorted capability-relevant pack tuple.  Empty == every pack
# config matches base (those packs do not change representable
# capability).
MODEL_INFEASIBLE_DELTAS: dict[
    tuple[str, ...],
    dict[str, dict[BodyName, tuple[frozenset[tuple[BodyName, MissionType]], frozenset[tuple[BodyName, MissionType]]]]],
] = {
    ('Stock',): {
        'generous': {
            BodyName.EVE: (frozenset({(BodyName.MOHO, MissionType.RETURN)}), frozenset()),
            BodyName.LAYTHE: (frozenset({(BodyName.EVE, MissionType.RETURN)}), frozenset()),
            BodyName.TYLO: (frozenset({(BodyName.EVE, MissionType.SAMPLE_RETURN)}), frozenset()),
        },
    },
}


# Ascent edges eligible for the ESCALATED build caps (rocket_math
# ESCALATED_*), applied by capability ONLY inside Apollo-split
# evaluations.  Probed offline by compute_escalated_edges — an edge is
# listed iff escalating it flips some max-kit mission feasible.  Home
# ascents are never listed here (hot-path constraint) — the separate
# allowlisted ESCALATED_HOME_ASCENT_EDGES below carries the approved
# exceptions.
ESCALATED_ASCENT_EDGES: frozenset[tuple[BodyName, EdgeType]] = frozenset({
    (BodyName.EVE, EdgeType.ATMOSPHERIC_ASCENT),
})

# HOME-ascent edges eligible for the ESCALATED caps on the PRIMARY
# evaluation (every mission from that home traverses its ascent, so
# this is a deliberate hot-path exception).  Operator-allowlisted in
# generate_feasibility._HOME_ESCALATION_ALLOWLIST and probe-verified
# to still flip feasibility; the probe can never add a home on its
# own.
ESCALATED_HOME_ASCENT_EDGES: frozenset[tuple[BodyName, EdgeType]] = frozenset({
    (BodyName.EVE, EdgeType.ATMOSPHERIC_ASCENT),
})


# (home, destination, mission_type) triples eligible for the multi-launch
# orbital-assembly retry: missions the probe verified a single launch can
# NEVER close at max kit (unlimited pad) but ≤3 docked launches can.
# Probed offline by compute_assembly_missions; consulted by capability's
# _assembly_candidate on the failure path only.
ASSEMBLY_ELIGIBLE_MISSIONS: frozenset[
    tuple[BodyName, BodyName, MissionType]] = frozenset({
    (BodyName.EVE, BodyName.POL, MissionType.RETURN),
    (BodyName.EVE, BodyName.VALL, MissionType.RETURN),
    (BodyName.KERBIN, BodyName.EVE, MissionType.SAMPLE_RETURN),
    (BodyName.TYLO, BodyName.EVE, MissionType.RETURN),
    (BodyName.TYLO, BodyName.EVE, MissionType.SAMPLE_RETURN),
})
