"""Static model-infeasible-locations table — checked in,
regenerated by ``worlds/ksp1/scripts/generate_feasibility.py``.

For each body that can serve as a starting body, lists the AP
location names whose mission the dv model cannot verify even
when the player has every progressive item at max tier and one
of every part in ``PART_DB``.  Goal rules that include any of
these locations fall back to the "all-parts collected" proxy
at completion-check time.

Entries are full AP location names (one per slot — e.g. three
``Eve Return 1..3`` entries for the three RETURN slots) so the
rules layer can filter Return vs Sample Return vs other mission
types independently.

This file is generated; do not hand-edit.  Re-run the script
whenever the dv model, mission graph, or part database changes.
"""
from __future__ import annotations

from worlds.ksp1.bodies import BodyName


MODEL_INFEASIBLE_LOCATIONS: dict[BodyName, frozenset[str]] = {
    BodyName.BOP: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3'}),
    BodyName.DRES: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.DUNA: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.EELOO: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.EVE: frozenset({'Bop Return 1', 'Bop Return 2', 'Bop Return 3', 'Bop Sample Return 1', 'Bop Sample Return 2', 'Bop Sample Return 3', 'Dres Return 1', 'Dres Return 2', 'Dres Return 3', 'Dres Sample Return 1', 'Dres Sample Return 2', 'Dres Sample Return 3', 'Duna Return 1', 'Duna Return 2', 'Duna Return 3', 'Duna Sample Return 1', 'Duna Sample Return 2', 'Duna Sample Return 3', 'Eeloo Return 1', 'Eeloo Return 2', 'Eeloo Return 3', 'Eeloo Sample Return 1', 'Eeloo Sample Return 2', 'Eeloo Sample Return 3', 'Gilly Return 1', 'Gilly Return 2', 'Gilly Return 3', 'Gilly Sample Return 1', 'Gilly Sample Return 2', 'Gilly Sample Return 3', 'Ike Return 1', 'Ike Return 2', 'Ike Return 3', 'Ike Sample Return 1', 'Ike Sample Return 2', 'Ike Sample Return 3', 'Kerbin Return 1', 'Kerbin Return 2', 'Kerbin Return 3', 'Kerbin Sample Return 1', 'Kerbin Sample Return 2', 'Kerbin Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3', 'Minmus Return 1', 'Minmus Return 2', 'Minmus Return 3', 'Minmus Sample Return 1', 'Minmus Sample Return 2', 'Minmus Sample Return 3', 'Moho Return 1', 'Moho Return 2', 'Moho Return 3', 'Moho Sample Return 1', 'Moho Sample Return 2', 'Moho Sample Return 3', 'Mun Return 1', 'Mun Return 2', 'Mun Return 3', 'Mun Sample Return 1', 'Mun Sample Return 2', 'Mun Sample Return 3', 'Pol Return 1', 'Pol Return 2', 'Pol Return 3', 'Pol Sample Return 1', 'Pol Sample Return 2', 'Pol Sample Return 3', 'Tylo Return 1', 'Tylo Return 2', 'Tylo Return 3', 'Tylo Sample Return 1', 'Tylo Sample Return 2', 'Tylo Sample Return 3', 'Vall Return 1', 'Vall Return 2', 'Vall Return 3', 'Vall Sample Return 1', 'Vall Sample Return 2', 'Vall Sample Return 3'}),
    BodyName.GILLY: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.IKE: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.KERBIN: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3', 'Tylo Return 1', 'Tylo Return 2', 'Tylo Return 3', 'Tylo Sample Return 1', 'Tylo Sample Return 2', 'Tylo Sample Return 3'}),
    BodyName.LAYTHE: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3'}),
    BodyName.MINMUS: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.MOHO: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.MUN: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Laythe Return 1', 'Laythe Return 2', 'Laythe Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.POL: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3'}),
    BodyName.TYLO: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3', 'Kerbin Sample Return 1', 'Kerbin Sample Return 2', 'Kerbin Sample Return 3', 'Laythe Sample Return 1', 'Laythe Sample Return 2', 'Laythe Sample Return 3'}),
    BodyName.VALL: frozenset({'Eve Return 1', 'Eve Return 2', 'Eve Return 3', 'Eve Sample Return 1', 'Eve Sample Return 2', 'Eve Sample Return 3'}),
}
