"""
Part data models and JSON-backed part database for KSP1 Archipelago.

All dataclasses are frozen (hashable, immutable).  The PART_DB dict maps
item-name strings (matching ITEM_TABLE in items.py) to lists of part objects
loaded from data/parts.json, which is generated by scripts/extract_parts.py
from real KSP cfg files.
"""
from __future__ import annotations

import json
import math
import pkgutil
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Union


# ---------------------------------------------------------------------------
# Capability flags — single source of truth for MiscEquipment.provides values
# ---------------------------------------------------------------------------

class CapabilityFlag(StrEnum):
    PROBE_CORE = "probe_core"
    CAPSULE = "capsule"
    REACTION_WHEEL = "reaction_wheel"
    RCS = "rcs"
    SOLAR_FIXED = "solar_fixed"
    SOLAR_RETRACTABLE = "solar_retractable"
    SOLAR_ARRAY_LARGE = "solar_array_large"
    RTG = "rtg"
    BATTERY_SMALL = "battery_small"
    BATTERY_LARGE = "battery_large"
    DOCKING_PORT = "docking_port"
    FUEL_LINE = "fuel_line"
    LADDER = "ladder"
    LAUNCH_CLAMP = "launch_clamp"
    ISRU = "isru"
    MULTI_MOUNT = "multi_mount"
    THERMOMETER = "thermometer"
    BAROMETER = "barometer"
    WHEEL = "wheel"
    AERO_CONTROL = "aero_control"
    SCIENCE_INSTRUMENT = "science_instrument"
    RELAY_T1 = "relay_t1"
    RELAY_T2 = "relay_t2"
    RELAY_T3 = "relay_t3"
    RELAY_T4 = "relay_t4"


# ---------------------------------------------------------------------------
# Part dataclasses
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Engine:
    name: str
    vac_isp: float          # seconds
    atm_isp: float          # seconds
    vac_thrust: float       # kN
    atm_thrust: float       # kN
    mass: float             # tonnes (dry engine mass only)
    throttleable: bool
    has_gimbal: bool
    size_class: float       # metres: 0.625, 1.25, 2.5, 3.75, 5.0
    fuel_type: str          # "lfo" | "lf" | "xenon" (derived tag)
    radial_mountable: bool = False  # True if engine has "srf" in bulkhead_profiles
    # Stock-resource names the engine consumes (excluding ElectricCharge),
    # sorted. Used for generic tank/engine compatibility.
    propellants: tuple[str, ...] = ()


@dataclass(frozen=True)
class FuelTank:
    name: str
    dry_mass: float         # tonnes
    fuel_mass: float        # tonnes at 100% fill (sum of all carried propellants)
    fuel_type: str          # "lfo" | "lf" | "xenon" | "monoprop" (derived tag)
    size_class: float       # metres
    max_count: int = 0      # 0 = unlimited; >0 caps optimizer tank count (adapters)
    # Per-propellant mass at 100% fill (tonnes), e.g. {"LiquidFuel": 0.5,
    # "Oxidizer": 0.5} for an LFO tank. Lets an engine that needs only a
    # subset of the carried propellants drain the rest — except MonoPropellant,
    # which cannot be drained (dedicated resource).
    fuel_masses: tuple[tuple[str, float], ...] = ()


@dataclass(frozen=True)
class SolidBooster:
    """SRB modeled as a combined engine+tank unit.  Always 100% fill."""
    name: str
    vac_isp: float
    atm_isp: float
    vac_thrust: float       # kN
    atm_thrust: float       # kN
    dry_mass: float         # tonnes (empty casing)
    fuel_mass: float        # tonnes (propellant)
    has_gimbal: bool        # always False for stock SRBs
    size_class: float
    radial_mountable: bool = False  # True if SRB has "srf" in bulkhead_profiles


@dataclass(frozen=True)
class HeatShield:
    name: str
    mass: float             # tonnes
    size_class: float       # metres — covers parts up to this diameter


@dataclass(frozen=True)
class Parachute:
    name: str
    mass: float             # tonnes
    drag_area: float        # effective drag area (m²), from KSP fullyDeployedDrag
    is_drogue: bool         # drogue chutes are NEVER counted in logic
    is_radial: bool = False # radial chutes mount on sides (unlimited); inline cap at 1


@dataclass(frozen=True)
class LandingLeg:
    name: str
    mass: float             # tonnes
    tier: int               # 1=small, 2=medium, 3=heavy


@dataclass(frozen=True)
class Decoupler:
    name: str
    mass: float
    kind: str               # "stack" | "radial"
    size_class: float


@dataclass(frozen=True)
class MiscEquipment:
    name: str
    mass: float
    provides: frozenset[CapabilityFlag]  # see CapabilityFlag enum for valid values


# ---------------------------------------------------------------------------
# Multi-mount adapter/coupler/plate table
# ---------------------------------------------------------------------------

# Cap for radial-mount engines/SRBs and radial-tank-mounting (KSP symmetry
# modes: 1x, 2x, 3x, 4x, 6x, 8x).
MAX_RADIAL_ENGINES: int = 8


@dataclass(frozen=True)
class MultiMount:
    """An adapter, coupler, or engine plate that enables multi-engine stages.

    min_tank_size: minimum tank size_class above the adapter (0.0 = no limit,
                   e.g. engine plates attach anywhere).
    engine_counts: mapping of engine_size_class → max engines mountable.
                   Lookup: find the smallest key >= the engine's size_class.
    _sorted_sizes: pre-sorted engine_counts keys for fast lookup (auto-set).
    """
    min_tank_size: float
    engine_counts: dict[float, int]
    _sorted_sizes: tuple[float, ...] = field(default=(), repr=False)

    def __post_init__(self) -> None:
        object.__setattr__(self, '_sorted_sizes',
                           tuple(sorted(self.engine_counts)))


MULTI_MOUNT_TABLE: dict[str, MultiMount] = {
    # Stock couplers (output 1.25m nodes)
    "stackBiCoupler.v2":     MultiMount(1.25, {1.25: 2}),
    "stackTriCoupler.v2":    MultiMount(1.25, {1.25: 3}),
    "stackQuadCoupler":      MultiMount(1.25, {1.25: 4}),
    # Stock adapters (2.5m input → 1.25m output)
    "mk2.1m.Bicoupler":     MultiMount(2.5,  {1.25: 2}),
    "adapterLargeSmallBi":   MultiMount(2.5,  {1.25: 2}),
    "adapterLargeSmallTri":  MultiMount(2.5,  {1.25: 3}),
    "adapterLargeSmallQuad": MultiMount(2.5,  {1.25: 4}),
    # Engine plates (Making History, no min_tank_size restriction)
    "EnginePlate5":   MultiMount(0.0, {0.625: 3}),                                       # EP-12
    "EnginePlate1p5": MultiMount(0.0, {0.625: 7}),                                       # EP-18
    "EnginePlate2":   MultiMount(0.0, {0.625: 9, 1.25: 3}),                              # EP-25
    "EnginePlate3":   MultiMount(0.0, {0.625: 9, 1.25: 7, 1.875: 3}),                    # EP-37
    "EnginePlate4":   MultiMount(0.0, {0.625: 9, 1.25: 9, 1.875: 7, 2.5: 3}),            # EP-50
    # Dual-purpose adapter (Making History) — also a fuel tank
    "Size4.EngineAdapter.01": MultiMount(3.75, {2.5: 5, 3.75: 1}),
}


# ---------------------------------------------------------------------------
# Type alias for any part
# ---------------------------------------------------------------------------

AnyPart = Union[Engine, FuelTank, SolidBooster, HeatShield, Parachute,
                LandingLeg, Decoupler, MiscEquipment]


# ---------------------------------------------------------------------------
# Lookup tables for building parts from cfg data
# ---------------------------------------------------------------------------

_RESOURCE_DENSITY: dict[str, float] = {
    "LiquidFuel": 0.005,
    "Oxidizer": 0.005,
    "SolidFuel": 0.0075,
    "MonoPropellant": 0.004,
    "XenonGas": 0.0001,
}

_BULKHEAD_DIAMETER: dict[str, float] = {
    "size0": 0.625,
    "size1": 1.25,
    "size1p5": 1.875,
    "size2": 2.5,
    "size3": 3.75,
    "size4": 5.0,
    "mk2": 2.5,
    "mk3": 3.75,
}


# ---------------------------------------------------------------------------
# Part mapping registry: cfg internal name → AP item name + type + overrides
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PartMapping:
    cfg_name: str           # key into parts.json (cfg-file internal name)
    part_type: type         # Engine, FuelTank, etc.
    title: str              # human-readable display name (for comments/UI only)
    offset: int             # stable item ID offset (1000+); see scripts/generate_registry.py
    overrides: dict = field(default_factory=dict)

    @property
    def ksp_name(self) -> str:
        """KSP runtime name (AvailablePart.name): underscores become dots."""
        return self.cfg_name.replace('_', '.')


PART_REGISTRY: list[PartMapping] = [
    # --- Engines (19) ---
    PartMapping("SSME", Engine, "S3 KS-25 \"Vector\" Liquid Fuel Engine", 1259),
    PartMapping("Size2LFB_v2", Engine, "LFB KR-1x2 \"Twin-Boar\" Liquid Fuel Engine", 1109),
    PartMapping("Size3AdvancedEngine", Engine, "Kerbodyne KR-2L+ \"Rhino\" Liquid Fuel Engine", 1105),
    PartMapping("Size3EngineCluster", Engine, "S3 KS-25x4 \"Mammoth\" Liquid Fuel Engine", 1260),
    PartMapping("engineLargeSkipper_v2", Engine, "RE-I5 \"Skipper\" Liquid Fuel Engine", 1230),
    PartMapping("ionEngine", Engine, "IX-6315 \"Dawn\" Electric Propulsion System", 1093),
    PartMapping("liquidEngine2-2_v2", Engine, "RE-L10 \"Poodle\" Liquid Fuel Engine", 1231),
    PartMapping("liquidEngine2_v2", Engine, "LV-T45 \"Swivel\" Liquid Fuel Engine", 1118),
    PartMapping("liquidEngine3_v2", Engine, "LV-909 \"Terrier\" Liquid Fuel Engine", 1115),
    PartMapping("liquidEngineMainsail_v2", Engine, "RE-M3 \"Mainsail\" Liquid Fuel Engine", 1232),
    PartMapping("liquidEngineMini_v2", Engine, "48-7S \"Spark\" Liquid Fuel Engine", 1003),
    PartMapping("liquidEngine_v2", Engine, "LV-T30 \"Reliant\" Liquid Fuel Engine", 1117),
    PartMapping("microEngine_v2", Engine, "LV-1 \"Ant\" Liquid Fuel Engine", 1113),
    PartMapping("nuclearEngine", Engine, "LV-N \"Nerv\" Atomic Rocket Motor", 1116),
    PartMapping("omsEngine", Engine, "O-10 \"Puff\" MonoPropellant Fuel Engine", 1193),
    PartMapping("radialEngineMini_v2", Engine, "LV-1R \"Spider\" Liquid Fuel Engine", 1114),
    PartMapping("radialLiquidEngine1-2", Engine, "Mk-55 \"Thud\" Liquid Fuel Engine", 1140),
    PartMapping("smallRadialEngine_v2", Engine, "24-77 \"Twitch\" Liquid Fuel Engine", 1001),
    PartMapping("toroidalAerospike", Engine, "T-1 Toroidal Aerospike \"Dart\" Liquid Fuel Engine", 1299),
    # --- Solid Rocket Boosters (10) ---
    PartMapping("Clydesdale", SolidBooster, "S2-33 \"Clydesdale\" Solid Fuel Booster", 1258),
    PartMapping("LaunchEscapeSystem", SolidBooster, "Launch Escape System", 1126),
    PartMapping("MassiveBooster", SolidBooster, "S1 SRB-KD25k \"Kickback\" Solid Fuel Booster", 1256),
    PartMapping("Mite", SolidBooster, "FM1 \"Mite\" Solid Fuel Booster", 1079),
    PartMapping("Shrimp", SolidBooster, "F3S0 \"Shrimp\" Solid Fuel Booster", 1066),
    PartMapping("Thoroughbred", SolidBooster, "S2-17 \"Thoroughbred\" Solid Fuel Booster", 1257),
    PartMapping("sepMotor1", SolidBooster, "Sepratron I", 1272),
    PartMapping("solidBooster1-1", SolidBooster, "BACC \"Thumper\" Solid Fuel Booster", 1021),
    PartMapping("solidBooster_sm_v2", SolidBooster, "RT-5 \"Flea\" Solid Fuel Booster", 1239),
    PartMapping("solidBooster_v2", SolidBooster, "RT-10 \"Hammer\" Solid Fuel Booster", 1238),
    # --- Fuel Tanks (49) ---
    PartMapping("MK1Fuselage", FuelTank, "Mk1 Liquid Fuel Fuselage", 1148),
    PartMapping("RCSFuelTank", FuelTank, "FL-R120 RCS Fuel Tank", 1072),
    PartMapping("RCSTank1-2", FuelTank, "FL-R750 RCS Fuel Tank", 1074),
    PartMapping("Rockomax16_BW", FuelTank, "Rockomax X200-16 Fuel Tank", 1250),
    PartMapping("Rockomax32_BW", FuelTank, "Rockomax X200-32 Fuel Tank", 1251),
    PartMapping("Rockomax64_BW", FuelTank, "Rockomax Jumbo-64 Fuel Tank", 1249),
    PartMapping("Rockomax8BW", FuelTank, "Rockomax X200-8 Fuel Tank", 1252),
    PartMapping("Size3LargeTank", FuelTank, "Kerbodyne S3-14400 Tank", 1106),
    PartMapping("Size3MediumTank", FuelTank, "Kerbodyne S3-7200 Tank", 1108),
    PartMapping("Size3SmallTank", FuelTank, "Kerbodyne S3-3600 Tank", 1107),
    PartMapping("Size3To2Adapter_v2", FuelTank, "Kerbodyne ADTP-2-3", 1104),
    PartMapping("adapterMk3-Mk2", FuelTank, "Mk3 to Mk2 Adapter", 1186),
    PartMapping("adapterMk3-Size2", FuelTank, "Mk3 to 2.5m Adapter", 1183),
    PartMapping("adapterMk3-Size2Slant", FuelTank, "Mk3 to 2.5m Adapter Slanted", 1184),
    PartMapping("adapterSize2-Mk2", FuelTank, "2.5m to Mk2 Adapter", 1000),
    PartMapping("adapterSize2-Size1", FuelTank, "C7 Brand Adapter - 2.5m to 1.25m", 1029),
    PartMapping("adapterSize2-Size1Slant", FuelTank, "C7 Brand Adapter Slanted - 2.5m to 1.25m", 1030),
    PartMapping("adapterSize3-Mk3", FuelTank, "Mk3 to 3.75m Adapter", 1185),
    PartMapping("externalTankCapsule", FuelTank, "R-11 'Baguette' External Tank", 1222),
    PartMapping("externalTankRound", FuelTank, "R-4 'Dumpling' External Tank", 1224),
    PartMapping("externalTankToroid", FuelTank, "R-12 'Doughnut' External Tank", 1223),
    PartMapping("fuelTank", FuelTank, "FL-T400 Fuel Tank", 1077),
    PartMapping("fuelTankSmall", FuelTank, "FL-T200 Fuel Tank", 1076),
    PartMapping("fuelTankSmallFlat", FuelTank, "FL-T100 Fuel Tank", 1075),
    PartMapping("fuelTank_long", FuelTank, "FL-T800 Fuel Tank", 1078),
    PartMapping("miniFuelTank", FuelTank, "Oscar-B Fuel Tank", 1201),
    PartMapping("miniFuselage", FuelTank, "Mk0 Liquid Fuel Fuselage", 1141),
    PartMapping("mk2Fuselage", FuelTank, "Mk2 Liquid Fuel Fuselage", 1160),
    PartMapping("mk2FuselageLongLFO", FuelTank, "Mk2 Rocket Fuel Fuselage", 1163),
    PartMapping("mk2FuselageShortLFO", FuelTank, "Mk2 Rocket Fuel Fuselage Short", 1164),
    PartMapping("mk2FuselageShortLiquid", FuelTank, "Mk2 Liquid Fuel Fuselage Short", 1161),
    PartMapping("mk2FuselageShortMono", FuelTank, "Mk2 Monopropellant Tank", 1162),
    PartMapping("mk2SpacePlaneAdapter", FuelTank, "Mk2 to 1.25m Adapter", 1165),
    PartMapping("mk2_1m_AdapterLong", FuelTank, "Mk2 to 1.25m Adapter Long", 1166),
    PartMapping("mk2_1m_Bicoupler", FuelTank, "Mk2 Bicoupler", 1153,
                {"max_count": 1}),
    PartMapping("mk3FuselageLFO_100", FuelTank, "Mk3 Rocket Fuel Fuselage Long", 1181),
    PartMapping("mk3FuselageLFO_25", FuelTank, "Mk3 Rocket Fuel Fuselage Short", 1182),
    PartMapping("mk3FuselageLFO_50", FuelTank, "Mk3 Rocket Fuel Fuselage", 1180),
    PartMapping("mk3FuselageLF_100", FuelTank, "Mk3 Liquid Fuel Fuselage Long", 1176),
    PartMapping("mk3FuselageLF_25", FuelTank, "Mk3 Liquid Fuel Fuselage Short", 1177),
    PartMapping("mk3FuselageLF_50", FuelTank, "Mk3 Liquid Fuel Fuselage", 1175),
    PartMapping("mk3FuselageMONO", FuelTank, "Mk3 Monopropellant Tank", 1178),
    PartMapping("noseConeAdapter", FuelTank, "NCS Adapter", 1191),
    PartMapping("radialRCSTank", FuelTank, "Stratus-V Roundified Monopropellant Tank", 1288),
    PartMapping("rcsTankMini", FuelTank, "FL-R20 RCS Fuel Tank", 1073),
    PartMapping("rcsTankRadialLong", FuelTank, "Stratus-V Cylindrified Monopropellant Tank", 1287),
    PartMapping("xenonTank", FuelTank, "PB-X150 Xenon Container", 1203),
    PartMapping("xenonTankLarge", FuelTank, "PB-X750 Xenon Container", 1205),
    PartMapping("xenonTankRadial", FuelTank, "PB-X50R Xenon Container", 1204),
    # --- Heat Shields (5) ---
    PartMapping("HeatShield0", HeatShield, "Heat Shield (0.625m)", 1087),
    PartMapping("HeatShield1", HeatShield, "Heat Shield (1.25m)", 1088),
    PartMapping("HeatShield2", HeatShield, "Heat Shield (2.5m)", 1090),
    PartMapping("HeatShield3", HeatShield, "Heat Shield (3.75m)", 1091),
    PartMapping("InflatableHeatShield", HeatShield, "Heat Shield (10m)", 1089),
    # --- Parachutes (5) ---
    PartMapping("parachuteDrogue", Parachute, "Mk25 Parachute", 1168,
                {"is_drogue": True}),
    PartMapping("parachuteLarge", Parachute, "Mk16-XL Parachute", 1152,
                {"is_drogue": False}),
    PartMapping("parachuteRadial", Parachute, "Mk2-R Radial-Mount Parachute", 1167,
                {"is_drogue": False, "is_radial": True}),
    PartMapping("parachuteSingle", Parachute, "Mk16 Parachute", 1151,
                {"is_drogue": False}),
    PartMapping("radialDrogue", Parachute, "Mk12-R Radial-Mount Drogue Chute", 1150,
                {"is_drogue": True, "is_radial": True}),
    # --- Landing Legs (3) ---
    PartMapping("landingLeg1", LandingLeg, "LT-1 Landing Struts", 1111,
                {"tier": 1}),
    PartMapping("landingLeg1-2", LandingLeg, "LT-2 Landing Strut", 1112,
                {"tier": 2}),
    PartMapping("miniLandingLeg", LandingLeg, "LT-05 Micro Landing Strut", 1110,
                {"tier": 1}),
    # --- Decouplers (11) ---
    PartMapping("Decoupler_0", Decoupler, "TD-06 Decoupler", 1300),
    PartMapping("Decoupler_1", Decoupler, "TD-12 Decoupler", 1301),
    PartMapping("Decoupler_2", Decoupler, "TD-25 Decoupler", 1302),
    PartMapping("Decoupler_3", Decoupler, "TD-37 Decoupler", 1303),
    PartMapping("Separator_0", Decoupler, "TS-06 Stack Separator", 1305),
    PartMapping("Separator_1", Decoupler, "TS-12 Stack Separator", 1306),
    PartMapping("Separator_2", Decoupler, "TS-25 Stack Separator", 1307),
    PartMapping("Separator_3", Decoupler, "TS-37 Stack Separator", 1308),
    PartMapping("radialDecoupler", Decoupler, "TT-38K Radial Decoupler", 1309),
    PartMapping("radialDecoupler1-2", Decoupler, "Hydraulic Detachment Manifold", 1092),
    PartMapping("radialDecoupler2", Decoupler, "TT-70 Radial Decoupler", 1310),
    # --- Misc Equipment (238) ---
    PartMapping("AdvancedCanard", MiscEquipment, "Advanced Canard", 1012,
                {"provides": frozenset()}),
    PartMapping("CanardController", MiscEquipment, "Standard Canard", 1284,
                {"provides": frozenset()}),
    PartMapping("CargoStorageUnit", MiscEquipment, "SEQ-24 Cargo Storage Unit", 1263,
                {"provides": frozenset()}),
    PartMapping("CircularIntake", MiscEquipment, "Circular Intake", 1033,
                {"provides": frozenset()}),
    PartMapping("ConformalStorageUnit", MiscEquipment, "SEQ-3C Conformal Storage Unit", 1265,
                {"provides": frozenset()}),
    PartMapping("FuelCell", MiscEquipment, "Fuel Cell", 1082,
                {"provides": frozenset()}),
    PartMapping("FuelCellArray", MiscEquipment, "Fuel Cell Array", 1083,
                {"provides": frozenset()}),
    PartMapping("GearFixed", MiscEquipment, "LY-01 Fixed Landing Gear", 1119,
                {"provides": frozenset({"wheel"})}),
    PartMapping("GearFree", MiscEquipment, "LY-05 Steerable Landing Gear", 1120,
                {"provides": frozenset({"wheel"})}),
    PartMapping("GearLarge", MiscEquipment, "LY-99 Extra Large Landing Gear", 1124,
                {"provides": frozenset({"wheel"})}),
    PartMapping("GearMedium", MiscEquipment, "LY-60 Large Landing Gear", 1123,
                {"provides": frozenset({"wheel"})}),
    PartMapping("GearSmall", MiscEquipment, "LY-35 Medium Landing Gear", 1122,
                {"provides": frozenset({"wheel"})}),
    PartMapping("GooExperiment", MiscEquipment, "Mystery Goo™ Containment Unit", 1190,
                {"provides": frozenset({"science_instrument"})}),
    PartMapping("GrapplingDevice", MiscEquipment, "Advanced Grabbing Unit", 1013,
                {"provides": frozenset()}),
    PartMapping("HECS2_ProbeCore", MiscEquipment, "Probodobodyne HECS2", 1214,
                {"provides": frozenset({"probe_core", "reaction_wheel"})}),
    PartMapping("HighGainAntenna", MiscEquipment, "Communotron HG-55", 1042,
                {"provides": frozenset({"relay_t3"})}),
    PartMapping("HighGainAntenna5_v2", MiscEquipment, "HG-5 High Gain Antenna", 1086,
                {"provides": frozenset({"relay_t1"})}),
    PartMapping("ISRU", MiscEquipment, "Convert-O-Tron 250", 1044,
                {"provides": frozenset({"isru"})}),
    PartMapping("InfraredTelescope", MiscEquipment, "SENTINEL Infrared Telescope", 1262,
                {"provides": frozenset()}),
    PartMapping("IntakeRadialLong", MiscEquipment, "Adjustable Ramp Intake (Radial)", 1011,
                {"provides": frozenset()}),
    PartMapping("JetEngine", MiscEquipment, "J-33 \"Wheesley\" Turbofan Engine", 1098,
                {"provides": frozenset()}),
    PartMapping("LargeTank", MiscEquipment, "Large Holding Tank", 1125,
                {"provides": frozenset()}),
    PartMapping("Large_Crewed_Lab", MiscEquipment, "Mobile Processing Lab MPL-LG-2", 1187,
                {"provides": frozenset({"capsule"})}),
    PartMapping("LgRadialSolarPanel", MiscEquipment, "OX-STAT-XL Photovoltaic Panels", 1199,
                {"provides": frozenset({"solar_fixed"})}),
    PartMapping("MK1CrewCabin", MiscEquipment, "Mk1 Crew Cabin", 1144,
                {"provides": frozenset({"capsule"})}),
    PartMapping("MK1IntakeFuselage", MiscEquipment, "Mk1 Diverterless Supersonic Intake", 1145,
                {"provides": frozenset()}),
    PartMapping("Magnetometer", MiscEquipment, "Magnetometer Boom", 1139,
                {"provides": frozenset()}),
    PartMapping("Mark1Cockpit", MiscEquipment, "Mk1 Cockpit", 1142,
                {"provides": frozenset({"capsule"})}),
    PartMapping("Mark2Cockpit", MiscEquipment, "Mk1 Inline Cockpit", 1146,
                {"provides": frozenset({"capsule"})}),
    PartMapping("MiniDrill", MiscEquipment, "Drill-O-Matic Junior' Mining Excavator", 1050,
                {"provides": frozenset()}),
    PartMapping("MiniISRU", MiscEquipment, "Convert-O-Tron 125", 1043,
                {"provides": frozenset({"isru"})}),
    PartMapping("Mk1FuselageStructural", MiscEquipment, "Structural Fuselage", 1289,
                {"provides": frozenset()}),
    PartMapping("MpoProbe", MiscEquipment, "MPO Probe", 1137,
                {"provides": frozenset({"probe_core"})}),
    PartMapping("MtmStage", MiscEquipment, "MTM Stage", 1138,
                {"provides": frozenset({"probe_core"})}),
    PartMapping("OrbitalScanner", MiscEquipment, "M4435 Narrow-Band Scanner", 1133,
                {"provides": frozenset()}),
    PartMapping("R8winglet", MiscEquipment, "AV-R8 Winglet", 1008,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("RAPIER", MiscEquipment, "CR-7 R.A.P.I.E.R. Engine", 1032,
                {"provides": frozenset()}),
    PartMapping("RCSBlock_v2", MiscEquipment, "RV-105 RCS Thruster Block", 1240,
                {"provides": frozenset({"rcs"})}),
    PartMapping("RCSLinearSmall", MiscEquipment, "Place Anywhere 1 Linear RCS Port", 1210,
                {"provides": frozenset({"rcs"})}),
    PartMapping("RCSblock_01_small", MiscEquipment, "RV-1X Variable Thruster Block", 1241,
                {"provides": frozenset({"rcs"})}),
    PartMapping("RadialDrill", MiscEquipment, "Drill-O-Matic' Mining Excavator", 1051,
                {"provides": frozenset()}),
    PartMapping("RadialOreTank", MiscEquipment, "Radial Holding Tank", 1242,
                {"provides": frozenset()}),
    PartMapping("RelayAntenna100", MiscEquipment, "RA-100 Relay Antenna", 1225,
                {"provides": frozenset({"relay_t4"})}),
    PartMapping("RelayAntenna5", MiscEquipment, "RA-2 Relay Antenna", 1227,
                {"provides": frozenset({"relay_t2"})}),
    PartMapping("RelayAntenna50", MiscEquipment, "RA-15 Relay Antenna", 1226,
                {"provides": frozenset({"relay_t3"})}),
    PartMapping("ReleaseValve", MiscEquipment, "FTE-1 Drain Valve", 1080,
                {"provides": frozenset()}),
    PartMapping("ScienceBox", MiscEquipment, "Experiment Storage Unit", 1065,
                {"provides": frozenset()}),
    PartMapping("ServiceBay_125_v2", MiscEquipment, "Service Bay (1.25m)", 1273,
                {"provides": frozenset()}),
    PartMapping("ServiceBay_250_v2", MiscEquipment, "Service Bay (2.5m)", 1274,
                {"provides": frozenset()}),
    PartMapping("SmallGearBay", MiscEquipment, "LY-10 Small Landing Gear", 1121,
                {"provides": frozenset({"wheel"})}),
    PartMapping("SmallTank", MiscEquipment, "Small Holding Tank", 1279,
                {"provides": frozenset()}),
    PartMapping("StandardCtrlSrf", MiscEquipment, "Elevon 1", 1058,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("SurfAntenna", MiscEquipment, "Communotron 16-S", 1039,
                {"provides": frozenset({"relay_t1"})}),
    PartMapping("SurfaceScanner", MiscEquipment, "Surface Scanning Module", 1295,
                {"provides": frozenset()}),
    PartMapping("SurveyScanner", MiscEquipment, "M700 Survey Scanner", 1134,
                {"provides": frozenset()}),
    PartMapping("adapterEngines", MiscEquipment, "Mk3 Engine Mount", 1174,
                {"provides": frozenset()}),
    PartMapping("adapterLargeSmallBi", MiscEquipment, "TVR-200L Stack Bi-Adapter", 1314,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("adapterLargeSmallQuad", MiscEquipment, "TVR-400L Stack Quad-Adapter", 1317,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("adapterLargeSmallTri", MiscEquipment, "TVR-300L Stack Tri-Adapter", 1316,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("adapterSmallMiniShort", MiscEquipment, "FL-A5 Adapter", 1071,
                {"provides": frozenset()}),
    PartMapping("adapterSmallMiniTall", MiscEquipment, "FL-A10 Adapter", 1070,
                {"provides": frozenset()}),
    PartMapping("advSasModule", MiscEquipment, "Advanced Inline Stabilizer", 1015,
                {"provides": frozenset({"reaction_wheel"})}),
    PartMapping("airScoop", MiscEquipment, "XM-G50 Radial Air Intake", 1334,
                {"provides": frozenset()}),
    PartMapping("airbrake1", MiscEquipment, "A.I.R.B.R.A.K.E.S", 1004,
                {"provides": frozenset()}),
    PartMapping("airlinerCtrlSrf", MiscEquipment, "FAT-455 Aeroplane Control Surface", 1067,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("airlinerMainWing", MiscEquipment, "FAT-455 Aeroplane Main Wing", 1068,
                {"provides": frozenset()}),
    PartMapping("airlinerTailFin", MiscEquipment, "FAT-455 Aeroplane Tail Fin", 1069,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("airplaneTail", MiscEquipment, "Tail Connector A", 1318,
                {"provides": frozenset()}),
    PartMapping("airplaneTailB", MiscEquipment, "Tail Connector B", 1319,
                {"provides": frozenset()}),
    PartMapping("asasmodule1-2", MiscEquipment, "Advanced Reaction Wheel Module, Large", 1018,
                {"provides": frozenset({"reaction_wheel"})}),
    PartMapping("avionicsNoseCone", MiscEquipment, "CH-J3 Fly-By-Wire Avionics Hub", 1031,
                {"provides": frozenset()}),
    PartMapping("basicFin", MiscEquipment, "Basic Fin", 1023,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("batteryBank", MiscEquipment, "Z-1k Rechargeable Battery Bank", 1336,
                {"provides": frozenset({"battery_large", "battery_small"})}),
    PartMapping("batteryBankLarge", MiscEquipment, "Z-4K Rechargeable Battery Bank", 1339,
                {"provides": frozenset({"battery_large", "battery_small"})}),
    PartMapping("batteryBankMini", MiscEquipment, "Z-200 Rechargeable Battery Bank", 1337,
                {"provides": frozenset({"battery_small"})}),
    PartMapping("batteryPack", MiscEquipment, "Z-100 Rechargeable Battery Pack", 1335,
                {"provides": frozenset({"battery_small"})}),
    PartMapping("cargoContainer", MiscEquipment, "SEQ-9 Container Module", 1266,
                {"provides": frozenset()}),
    PartMapping("commDish", MiscEquipment, "Communotron 88-88", 1040,
                {"provides": frozenset({"relay_t4"})}),
    PartMapping("crewCabin", MiscEquipment, "PPD-10 Hitchhiker Storage Container", 1206,
                {"provides": frozenset({"capsule"})}),
    PartMapping("cupola", MiscEquipment, "PPD-12 Cupola Module", 1207,
                {"provides": frozenset({"capsule"})}),
    PartMapping("deltaWing", MiscEquipment, "Delta Wing", 1046,
                {"provides": frozenset()}),
    PartMapping("delta_small", MiscEquipment, "Small Delta Wing", 1277,
                {"provides": frozenset()}),
    PartMapping("dockingPort1", MiscEquipment, "Clamp-O-Tron Shielded Docking Port", 1037,
                {"provides": frozenset({"docking_port"})}),
    PartMapping("dockingPort2", MiscEquipment, "Clamp-O-Tron Docking Port", 1034,
                {"provides": frozenset({"docking_port"})}),
    PartMapping("dockingPort3", MiscEquipment, "Clamp-O-Tron Docking Port Jr.", 1035,
                {"provides": frozenset({"docking_port"})}),
    PartMapping("dockingPortLarge", MiscEquipment, "Clamp-O-Tron Docking Port Sr.", 1036,
                {"provides": frozenset({"docking_port"})}),
    PartMapping("dockingPortLateral", MiscEquipment, "Inline Clamp-O-Tron", 1096,
                {"provides": frozenset({"docking_port"})}),
    PartMapping("domeLight1", MiscEquipment, "Domelight Mk1", 1048,
                {"provides": frozenset()}),
    PartMapping("elevon2", MiscEquipment, "Elevon 2", 1059,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("elevon3", MiscEquipment, "Elevon 3", 1060,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("elevon5", MiscEquipment, "Elevon 5", 1062,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("evaChute", MiscEquipment, "Personal Parachute", 1209,
                {"provides": frozenset()}),
    PartMapping("evaCylinder", MiscEquipment, "EVA Fuel Cylinders", 1055,
                {"provides": frozenset()}),
    PartMapping("evaJetpack", MiscEquipment, "EVA Jetpack", 1056,
                {"provides": frozenset()}),
    PartMapping("evaRepairKit", MiscEquipment, "EVA Repair Kit", 1057,
                {"provides": frozenset()}),
    PartMapping("evaScienceKit", MiscEquipment, "EVA Experiments Kit", 1054,
                {"provides": frozenset()}),
    PartMapping("fairingSize1", MiscEquipment, "AE-FF1 Airstream Protective Shell (1.25m)", 1005,
                {"provides": frozenset()}),
    PartMapping("fairingSize2", MiscEquipment, "AE-FF2 Airstream Protective Shell (2.5m)", 1006,
                {"provides": frozenset()}),
    PartMapping("fairingSize3", MiscEquipment, "AE-FF3 Airstream Protective Shell (3.75m)", 1007,
                {"provides": frozenset()}),
    PartMapping("fireworksLauncherBig", MiscEquipment, "Starshot-32", 1285,
                {"provides": frozenset()}),
    PartMapping("fireworksLauncherSmall", MiscEquipment, "Starshot-8", 1286,
                {"provides": frozenset()}),
    PartMapping("flagPartFlat", MiscEquipment, "RFP-F Flag Flat", 1237,
                {"provides": frozenset()}),
    PartMapping("flagPartSize0", MiscEquipment, "RFP-0 Flag (.625m)", 1233,
                {"provides": frozenset()}),
    PartMapping("flagPartSize1", MiscEquipment, "RFP-1 Flag  (1.25m)", 1234,
                {"provides": frozenset()}),
    PartMapping("flagPartSize2", MiscEquipment, "RFP-2 Flag  (2.5m)", 1235,
                {"provides": frozenset()}),
    PartMapping("flagPartSize3", MiscEquipment, "RFP-3 Flag  (3.75m)", 1236,
                {"provides": frozenset()}),
    PartMapping("foldingRadLarge", MiscEquipment, "Thermal Control System (large)", 1322,
                {"provides": frozenset()}),
    PartMapping("foldingRadMed", MiscEquipment, "Thermal Control System (medium)", 1323,
                {"provides": frozenset()}),
    PartMapping("foldingRadSmall", MiscEquipment, "Thermal Control System (small)", 1324,
                {"provides": frozenset()}),
    PartMapping("fuelLine", MiscEquipment, "FTX-2 External Fuel Duct", 1081,
                {"provides": frozenset({"fuel_line"})}),
    PartMapping("groundAnchor", MiscEquipment, "Stamp-O-Tron Ground Anchor", 1283,
                {"provides": frozenset()}),
    PartMapping("groundLight1", MiscEquipment, "Work Lamp - Small", 1332,
                {"provides": frozenset()}),
    PartMapping("groundLight2", MiscEquipment, "Work Lamp - Stand", 1333,
                {"provides": frozenset()}),
    PartMapping("ksp_r_largeBatteryPack", MiscEquipment, "Z-400 Rechargeable Battery", 1338,
                {"provides": frozenset({"battery_small"})}),
    PartMapping("ladder1", MiscEquipment, "Pegasus I Mobility Enhancer", 1208,
                {"provides": frozenset({"ladder"})}),
    PartMapping("landerCabinSmall", MiscEquipment, "Mk1 Lander Can", 1147,
                {"provides": frozenset({"capsule"})}),
    PartMapping("largeAdapter", MiscEquipment, "Rockomax Brand Adapter", 1246,
                {"provides": frozenset()}),
    PartMapping("largeAdapter2", MiscEquipment, "Rockomax Brand Adapter 02", 1247,
                {"provides": frozenset()}),
    PartMapping("largeSolarPanel", MiscEquipment, "Gigantor XL Solar Array", 1085,
                {"provides": frozenset({"solar_array_large", "solar_retractable"})}),
    PartMapping("launchClamp1", MiscEquipment, "TT18-A Launch Stability Enhancer", 1311,
                {"provides": frozenset({"launch_clamp"})}),
    PartMapping("linearRcs", MiscEquipment, "Place-Anywhere 7 Linear RCS Port", 1211,
                {"provides": frozenset({"rcs"})}),
    PartMapping("longAntenna", MiscEquipment, "Communotron 16", 1038,
                {"provides": frozenset({"relay_t1"})}),
    PartMapping("mediumDishAntenna", MiscEquipment, "Communotron DTS-M1", 1041,
                {"provides": frozenset({"relay_t2"})}),
    PartMapping("miniIntake", MiscEquipment, "Small Circular Intake", 1276,
                {"provides": frozenset()}),
    PartMapping("miniJetEngine", MiscEquipment, "J-20 \"Juno\" Basic Jet Engine", 1097,
                {"provides": frozenset()}),
    PartMapping("mk1-3pod", MiscEquipment, "Mk1-3 Command Pod", 1149,
                {"provides": frozenset({"capsule", "reaction_wheel"})}),
    PartMapping("mk1pod_v2", MiscEquipment, "Mk1 Command Pod", 1143,
                {"provides": frozenset({"capsule", "reaction_wheel"})}),
    PartMapping("mk2CargoBayL", MiscEquipment, "Mk2 Cargo Bay CRG-08", 1155,
                {"provides": frozenset()}),
    PartMapping("mk2CargoBayS", MiscEquipment, "Mk2 Cargo Bay CRG-04", 1154,
                {"provides": frozenset()}),
    PartMapping("mk2Cockpit_Inline", MiscEquipment, "Mk2 Inline Cockpit", 1158,
                {"provides": frozenset({"capsule"})}),
    PartMapping("mk2Cockpit_Standard", MiscEquipment, "Mk2 Cockpit", 1157,
                {"provides": frozenset({"capsule"})}),
    PartMapping("mk2CrewCabin", MiscEquipment, "MK2 Crew Cabin", 1135,
                {"provides": frozenset({"capsule"})}),
    PartMapping("mk2DockingPort", MiscEquipment, "Mk2 Clamp-O-Tron", 1156,
                {"provides": frozenset({"docking_port"})}),
    PartMapping("mk2DroneCore", MiscEquipment, "MK2 Drone Core", 1136,
                {"provides": frozenset({"probe_core", "reaction_wheel"})}),
    PartMapping("mk2LanderCabin_v2", MiscEquipment, "Mk2 Lander Can", 1159,
                {"provides": frozenset({"capsule"})}),
    PartMapping("mk3CargoBayL", MiscEquipment, "Mk3 Cargo Bay CRG-100", 1169,
                {"provides": frozenset()}),
    PartMapping("mk3CargoBayM", MiscEquipment, "Mk3 Cargo Bay CRG-50", 1171,
                {"provides": frozenset()}),
    PartMapping("mk3CargoBayS", MiscEquipment, "Mk3 Cargo Bay CRG-25", 1170,
                {"provides": frozenset()}),
    PartMapping("mk3CargoRamp", MiscEquipment, "Mk3 Cargo Ramp", 1172,
                {"provides": frozenset()}),
    PartMapping("mk3Cockpit_Shuttle", MiscEquipment, "Mk3 Cockpit", 1173,
                {"provides": frozenset({"capsule", "reaction_wheel"})}),
    PartMapping("mk3CrewCabin", MiscEquipment, "Mk3 Passenger Module", 1179,
                {"provides": frozenset({"capsule"})}),
    PartMapping("nacelleBody", MiscEquipment, "Engine Nacelle", 1063,
                {"provides": frozenset()}),
    PartMapping("navLight1", MiscEquipment, "Navigation Light Mk1", 1192,
                {"provides": frozenset()}),
    PartMapping("noseCone", MiscEquipment, "Aerodynamic Nose Cone", 1019,
                {"provides": frozenset()}),
    PartMapping("pointyNoseConeA", MiscEquipment, "Advanced Nose Cone - Type A", 1016,
                {"provides": frozenset()}),
    PartMapping("pointyNoseConeB", MiscEquipment, "Advanced Nose Cone - Type B", 1017,
                {"provides": frozenset()}),
    PartMapping("probeCoreCube", MiscEquipment, "Probodobodyne QBE", 1217,
                {"provides": frozenset({"probe_core"})}),
    PartMapping("probeCoreHex_v2", MiscEquipment, "Probodobodyne HECS", 1213,
                {"provides": frozenset({"probe_core", "reaction_wheel"})}),
    PartMapping("probeCoreOcto2_v2", MiscEquipment, "Probodobodyne OKTO2", 1216,
                {"provides": frozenset({"probe_core"})}),
    PartMapping("probeCoreOcto_v2", MiscEquipment, "Probodobodyne OKTO", 1215,
                {"provides": frozenset({"probe_core"})}),
    PartMapping("probeCoreSphere_v2", MiscEquipment, "Probodobodyne Stayputnik", 1219,
                {"provides": frozenset({"probe_core"})}),
    PartMapping("probeStackLarge", MiscEquipment, "RC-L01 Remote Guidance Unit", 1229,
                {"provides": frozenset({"probe_core", "reaction_wheel"})}),
    PartMapping("probeStackSmall", MiscEquipment, "RC-001S Remote Guidance Unit", 1228,
                {"provides": frozenset({"probe_core", "reaction_wheel"})}),
    PartMapping("radPanelEdge", MiscEquipment, "Radiator Panel (edge)", 1243,
                {"provides": frozenset()}),
    PartMapping("radPanelLg", MiscEquipment, "Radiator Panel (large)", 1244,
                {"provides": frozenset()}),
    PartMapping("radPanelSm", MiscEquipment, "Radiator Panel (small)", 1245,
                {"provides": frozenset()}),
    PartMapping("radialEngineBody", MiscEquipment, "Engine Pre-cooler", 1064,
                {"provides": frozenset()}),
    PartMapping("ramAirIntake", MiscEquipment, "Adjustable Ramp Intake", 1010,
                {"provides": frozenset()}),
    PartMapping("rocketNoseConeSize3", MiscEquipment, "Protective Rocket Nose Cone Mk12A", 1220,
                {"provides": frozenset()}),
    PartMapping("rocketNoseCone_v3", MiscEquipment, "Protective Rocket Nose Cone Mk7", 1221,
                {"provides": frozenset()}),
    PartMapping("roverBody_v2", MiscEquipment, "Probodobodyne RoveMate", 1218,
                {"provides": frozenset({"probe_core"})}),
    PartMapping("roverWheel1", MiscEquipment, "RoveMax Model M1", 1253,
                {"provides": frozenset({"wheel"})}),
    PartMapping("roverWheel2", MiscEquipment, "RoveMax Model S2", 1254,
                {"provides": frozenset({"wheel"})}),
    PartMapping("roverWheel3", MiscEquipment, "RoveMax Model XL3", 1255,
                {"provides": frozenset({"wheel"})}),
    PartMapping("rtg", MiscEquipment, "PB-NUK Radioisotope Thermoelectric Generator", 1202,
                {"provides": frozenset({"rtg"})}),
    PartMapping("sasModule", MiscEquipment, "Small Inline Reaction Wheel", 1280,
                {"provides": frozenset({"reaction_wheel"})}),
    PartMapping("science_module", MiscEquipment, "SC-9001 Science Jr.", 1261,
                {"provides": frozenset({"science_instrument"})}),
    PartMapping("seatExternalCmd", MiscEquipment, "EAS-1 External Command Seat", 1052,
                {"provides": frozenset({"capsule"})}),
    PartMapping("sensorAccelerometer", MiscEquipment, "Double-C Seismic Accelerometer", 1049,
                {"provides": frozenset({"science_instrument"})}),
    PartMapping("sensorAtmosphere", MiscEquipment, "Atmospheric Fluid Spectro-Variometer", 1020,
                {"provides": frozenset({"science_instrument"})}),
    PartMapping("sensorBarometer", MiscEquipment, "PresMat Barometer", 1212,
                {"provides": frozenset({"barometer", "science_instrument"})}),
    PartMapping("sensorGravimeter", MiscEquipment, "GRAVMAX Negative Gravioli Detector", 1084,
                {"provides": frozenset({"science_instrument"})}),
    PartMapping("sensorThermometer", MiscEquipment, "2HOT Thermometer", 1002,
                {"provides": frozenset({"science_instrument", "thermometer"})}),
    PartMapping("shockConeIntake", MiscEquipment, "Shock Cone Intake", 1275,
                {"provides": frozenset()}),
    PartMapping("smallCargoContainer", MiscEquipment, "SEQ-3 Cargo Storage Unit", 1264,
                {"provides": frozenset()}),
    PartMapping("smallClaw", MiscEquipment, "Advanced Grabbing Unit Jr.", 1014,
                {"provides": frozenset()}),
    PartMapping("smallCtrlSrf", MiscEquipment, "Elevon 4", 1061,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("smallHardpoint", MiscEquipment, "Small Hardpoint", 1278,
                {"provides": frozenset()}),
    PartMapping("solarPanelOX10C", MiscEquipment, "OX-10C Photovoltaic Panels", 1194,
                {"provides": frozenset({"solar_fixed"})}),
    PartMapping("solarPanelOX10L", MiscEquipment, "OX-10L 1x5 Photovoltaic Panels", 1195,
                {"provides": frozenset({"solar_retractable"})}),
    PartMapping("solarPanelSP10C", MiscEquipment, "SP-10C Photovoltaic Panels", 1267,
                {"provides": frozenset({"solar_fixed"})}),
    PartMapping("solarPanelSP10L", MiscEquipment, "SP-10L 1x5 Photovoltaic Panels", 1268,
                {"provides": frozenset({"solar_retractable"})}),
    PartMapping("solarPanels1", MiscEquipment, "SP-W 3x2 Photovoltaic Panels", 1270,
                {"provides": frozenset({"solar_retractable"})}),
    PartMapping("solarPanels2", MiscEquipment, "SP-L 1x6 Photovoltaic Panels", 1269,
                {"provides": frozenset({"solar_retractable"})}),
    PartMapping("solarPanels3", MiscEquipment, "OX-4W 3x2 Photovoltaic Panels", 1197,
                {"provides": frozenset({"solar_retractable"})}),
    PartMapping("solarPanels4", MiscEquipment, "OX-4L 1x6 Photovoltaic Panels", 1196,
                {"provides": frozenset({"solar_retractable"})}),
    PartMapping("solarPanels5", MiscEquipment, "OX-STAT Photovoltaic Panels", 1198,
                {"provides": frozenset({"solar_fixed"})}),
    PartMapping("spotLight1_v2", MiscEquipment, "Illuminator Mk1", 1094,
                {"provides": frozenset()}),
    PartMapping("spotLight2_v2", MiscEquipment, "Illuminator Mk2", 1095,
                {"provides": frozenset()}),
    PartMapping("spotLight3", MiscEquipment, "Spotlight Mk1", 1282,
                {"provides": frozenset()}),
    PartMapping("stackBiCoupler_v2", MiscEquipment, "TVR-200 Stack Bi-Coupler", 1313,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("stackPoint1", MiscEquipment, "BZ-52 Radial Attachment Point", 1022,
                {"provides": frozenset()}),
    PartMapping("stackQuadCoupler", MiscEquipment, "TVR-2160C Mk2 Stack Quad-Coupler", 1315,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("stackTriCoupler_v2", MiscEquipment, "TVR-1180C Mk1 Stack Tri-Coupler", 1312,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("standardNoseCone", MiscEquipment, "Small Nose Cone", 1281,
                {"provides": frozenset()}),
    PartMapping("stationHub", MiscEquipment, "Rockomax HubMax Multi-Point Connector", 1248,
                {"provides": frozenset()}),
    PartMapping("stripLight1", MiscEquipment, "LightStrip Mk1", 1127,
                {"provides": frozenset()}),
    PartMapping("structuralIBeam1", MiscEquipment, "M-Beam 650 I-Beam", 1132,
                {"provides": frozenset()}),
    PartMapping("structuralIBeam2", MiscEquipment, "M-Beam 200 I-Beam", 1130,
                {"provides": frozenset()}),
    PartMapping("structuralIBeam3", MiscEquipment, "M-Beam 200 I-Beam Pocket Edition", 1131,
                {"provides": frozenset()}),
    PartMapping("structuralMiniNode", MiscEquipment, "The Not-Rockomax Micronode", 1321,
                {"provides": frozenset()}),
    PartMapping("structuralPanel1", MiscEquipment, "M-1x1 Structural Panel", 1128,
                {"provides": frozenset()}),
    PartMapping("structuralPanel2", MiscEquipment, "M-2x2 Structural Panel", 1129,
                {"provides": frozenset()}),
    PartMapping("structuralPylon", MiscEquipment, "Structural Pylon", 1290,
                {"provides": frozenset()}),
    PartMapping("structuralWing", MiscEquipment, "Structural Wing Type A", 1291,
                {"provides": frozenset()}),
    PartMapping("structuralWing2", MiscEquipment, "Structural Wing Type B", 1292,
                {"provides": frozenset()}),
    PartMapping("structuralWing3", MiscEquipment, "Structural Wing Type C", 1293,
                {"provides": frozenset()}),
    PartMapping("structuralWing4", MiscEquipment, "Structural Wing Type D", 1294,
                {"provides": frozenset()}),
    PartMapping("strutConnector", MiscEquipment, "EAS-4 Strut Connector", 1053,
                {"provides": frozenset()}),
    PartMapping("strutCube", MiscEquipment, "Cubic Octagonal Strut", 1045,
                {"provides": frozenset()}),
    PartMapping("strutOcto", MiscEquipment, "Octagonal Strut", 1200,
                {"provides": frozenset()}),
    PartMapping("sweptWing", MiscEquipment, "Swept Wings", 1298,
                {"provides": frozenset()}),
    PartMapping("sweptWing1", MiscEquipment, "Swept Wing Type A", 1296,
                {"provides": frozenset()}),
    PartMapping("sweptWing2", MiscEquipment, "Swept Wing Type B", 1297,
                {"provides": frozenset()}),
    PartMapping("tailfin", MiscEquipment, "Tail Fin", 1320,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("telescopicLadder", MiscEquipment, "Kelus Mobility Enhancer", 1102,
                {"provides": frozenset({"ladder"})}),
    PartMapping("telescopicLadderBay", MiscEquipment, "Kelus-LV Bay Mobility Enhancer", 1103,
                {"provides": frozenset({"ladder"})}),
    PartMapping("trussAdapter", MiscEquipment, "Modular Girder Adapter", 1188,
                {"provides": frozenset()}),
    PartMapping("trussPiece1x", MiscEquipment, "Modular Girder Segment", 1189,
                {"provides": frozenset()}),
    PartMapping("trussPiece3x", MiscEquipment, "Segment XL", 1271,
                {"provides": frozenset()}),
    PartMapping("turboFanEngine", MiscEquipment, "J-X4 \"Whiplash\" Turbo Ramjet Engine", 1101,
                {"provides": frozenset()}),
    PartMapping("turboFanSize2", MiscEquipment, "J-90 \"Goliath\" Turbofan Engine", 1100,
                {"provides": frozenset()}),
    PartMapping("turboJet", MiscEquipment, "J-404 \"Panther\" Afterburning Turbofan", 1099,
                {"provides": frozenset()}),
    PartMapping("vernierEngine", MiscEquipment, "Vernor Engine", 1325,
                {"provides": frozenset({"rcs"})}),
    PartMapping("wheelMed", MiscEquipment, "TR-2L Ruggedized Vehicular Wheel", 1304,
                {"provides": frozenset({"wheel"})}),
    PartMapping("wingConnector", MiscEquipment, "Wing Connector Type A", 1326,
                {"provides": frozenset()}),
    PartMapping("wingConnector2", MiscEquipment, "Wing Connector Type B", 1327,
                {"provides": frozenset()}),
    PartMapping("wingConnector3", MiscEquipment, "Wing Connector Type C", 1328,
                {"provides": frozenset()}),
    PartMapping("wingConnector4", MiscEquipment, "Wing Connector Type D", 1329,
                {"provides": frozenset()}),
    PartMapping("wingConnector5", MiscEquipment, "Wing Connector Type E", 1330,
                {"provides": frozenset()}),
    PartMapping("wingShuttleDelta", MiscEquipment, "Big-S Delta Wing", 1024,
                {"provides": frozenset()}),
    PartMapping("wingShuttleElevon1", MiscEquipment, "Big-S Elevon 1", 1025,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("wingShuttleElevon2", MiscEquipment, "Big-S Elevon 2", 1026,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("wingShuttleRudder", MiscEquipment, "Big-S Spaceplane Tail Fin", 1027,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("wingShuttleStrake", MiscEquipment, "Big-S Wing Strake", 1028,
                {"provides": frozenset()}),
    PartMapping("wingStrake", MiscEquipment, "Wing Strake", 1331,
                {"provides": frozenset()}),
    PartMapping("winglet", MiscEquipment, "AV-T1 Winglet", 1009,
                {"provides": frozenset({"aero_control"})}),
    PartMapping("winglet3", MiscEquipment, "Delta-Deluxe Winglet", 1047,
                {"provides": frozenset({"aero_control"})}),
    # ===================================================================
    # Making History DLC parts (offsets 1400+)
    # ===================================================================
    # --- MH Engines (7) ---
    PartMapping("LiquidEngineKE-1", Engine, 'Kerbodyne KE-1 "Mastodon" Liquid Fuel Engine', 1400),
    PartMapping("LiquidEngineLV-T91", Engine, 'LV-T91 "Cheetah" Liquid Fuel Engine', 1401),
    PartMapping("LiquidEngineLV-TX87", Engine, 'LV-TX87 "Bobcat" Liquid Fuel Engine', 1402),
    PartMapping("LiquidEngineRE-I2", Engine, 'RE-I2 "Skiff" Liquid Fuel Engine', 1403),
    PartMapping("LiquidEngineRE-J10", Engine, 'RE-J10 "Wolfhound" Liquid Fuel Engine', 1404),
    PartMapping("LiquidEngineRK-7", Engine, 'RK-7 "Kodiak" Liquid Fuel Engine', 1405),
    PartMapping("LiquidEngineRV-1", Engine, 'RV-1 "Cub" Vernier Engine', 1406),
    # --- MH Solid Rocket Boosters (1) ---
    PartMapping("Pollux", SolidBooster, 'THK "Pollux" Solid Fuel Booster', 1407),
    # --- MH Fuel Tanks (17) ---
    PartMapping("Size1p5_Tank_01", FuelTank, "FL-TX220 Fuel Tank", 1410),
    PartMapping("Size1p5_Tank_02", FuelTank, "FL-TX440 Fuel Tank", 1411),
    PartMapping("Size1p5_Tank_03", FuelTank, "FL-TX900 Fuel Tank", 1412),
    PartMapping("Size1p5_Tank_04", FuelTank, "FL-TX1800 Fuel Tank", 1413),
    PartMapping("Size1p5_Tank_05", FuelTank, "FL-C1000 Fuel Tank", 1414),
    PartMapping("Size1p5_Size0_Adapter_01", FuelTank, "FL-A150 Fuel Tank Adapter", 1415),
    PartMapping("Size1p5_Size1_Adapter_01", FuelTank, "FL-A151L Fuel Tank Adapter", 1416),
    PartMapping("Size1p5_Size1_Adapter_02", FuelTank, "FL-A151S Fuel Tank Adapter", 1417),
    PartMapping("Size1p5_Size2_Adapter_01", FuelTank, "FL-A215 Fuel Tank Adapter", 1418),
    PartMapping("Size1p5_Monoprop", FuelTank, "FL-R400 RCS Fuel Tank", 1419),
    PartMapping("Size4_Tank_01", FuelTank, "Kerbodyne S4-64 Fuel Tank", 1420),
    PartMapping("Size4_Tank_02", FuelTank, "Kerbodyne S4-128 Fuel Tank", 1421),
    PartMapping("Size4_Tank_03", FuelTank, "Kerbodyne S4-256 Fuel Tank", 1422),
    PartMapping("Size4_Tank_04", FuelTank, "Kerbodyne S4-512 Fuel Tank", 1423),
    PartMapping("Size3_Size4_Adapter_01", FuelTank, "Kerbodyne S3-S4 Adapter Tank", 1424),
    PartMapping("Size4_EngineAdapter_01", FuelTank, "Kerbodyne Engine Cluster Adapter Tank", 1425,
                {"max_count": 1}),
    PartMapping("monopropMiniSphere", FuelTank, "Stratus-V Minified Monopropellant Tank", 1426),
    # --- MH Heat Shield (1) ---
    PartMapping("HeatShield1p5", HeatShield, "Heat Shield (1.875m)", 1430),
    # --- MH Decouplers (5) ---
    PartMapping("Decoupler_1p5", Decoupler, "TD-18 Decoupler", 1431),
    PartMapping("Decoupler_4", Decoupler, "TD-50 Decoupler", 1432),
    PartMapping("Separator_1p5", Decoupler, "TS-18 Stack Separator", 1433),
    PartMapping("Separator_4", Decoupler, "TS-50 Stack Separator", 1434),
    PartMapping("Size1p5_Strut_Decoupler", Decoupler, "Size 1.5 Decoupler", 1435),
    # --- MH Engine Plates (5, MiscEquipment with multi_mount) ---
    PartMapping("EnginePlate5", MiscEquipment, "EP-12 Engine Plate", 1440,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("EnginePlate1p5", MiscEquipment, "EP-18 Engine Plate", 1441,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("EnginePlate2", MiscEquipment, "EP-25 Engine Plate", 1442,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("EnginePlate3", MiscEquipment, "EP-37 Engine Plate", 1443,
                {"provides": frozenset({"multi_mount"})}),
    PartMapping("EnginePlate4", MiscEquipment, "EP-50 Engine Plate", 1444,
                {"provides": frozenset({"multi_mount"})}),
    # --- MH Command Pods / Capsules (5) ---
    PartMapping("kv1Pod", MiscEquipment, "KV-1 'Onion' Reentry Module", 1450,
                {"provides": frozenset({"capsule"})}),
    PartMapping("kv2Pod", MiscEquipment, "KV-2 'Onion' Reentry Module", 1451,
                {"provides": frozenset({"capsule"})}),
    PartMapping("kv3Pod", MiscEquipment, "KV-3 'Tato' Reentry Module", 1452,
                {"provides": frozenset({"capsule"})}),
    PartMapping("Mk2Pod", MiscEquipment, "Mk2 Command Pod", 1453,
                {"provides": frozenset({"capsule", "reaction_wheel"})}),
    PartMapping("MEMLander", MiscEquipment, "Munar Excursion Module (M.E.M.)", 1454,
                {"provides": frozenset({"capsule"})}),
    # --- MH Service Modules & Other (25) ---
    PartMapping("ServiceModule18", MiscEquipment, "SM-18 Service Module", 1460,
                {"provides": frozenset()}),
    PartMapping("ServiceModule25", MiscEquipment, "SM-25 Service Module", 1461,
                {"provides": frozenset()}),
    PartMapping("Size1to0ServiceModule", MiscEquipment, "SM-6A Service Module", 1462,
                {"provides": frozenset()}),
    PartMapping("InflatableAirlock", MiscEquipment, "Inflatable Airlock", 1463,
                {"provides": frozenset()}),
    PartMapping("fairingSize1p5", MiscEquipment, "AE-FF1.5 Airstream Protective Shell (1.875m)", 1464,
                {"provides": frozenset()}),
    PartMapping("fairingSize4", MiscEquipment, "AE-FF5 Airstream Protective Shell (5m)", 1465,
                {"provides": frozenset()}),
    PartMapping("Size_1_5_Cone", MiscEquipment, "Protective Rocket Nosecone Mk5A", 1466,
                {"provides": frozenset()}),
    PartMapping("rocketNoseConeSize4", MiscEquipment, "Protective Nose Cone Mk16A", 1467,
                {"provides": frozenset()}),
    PartMapping("roverWheelM1-F", MiscEquipment, "RoveMax M1-F Rover Wheel", 1468,
                {"provides": frozenset({"wheel"})}),
    PartMapping("EquiTriangle0", MiscEquipment, "SP-T06 Structural Panel", 1470,
                {"provides": frozenset()}),
    PartMapping("EquiTriangle1", MiscEquipment, "SP-T12 Structural Panel", 1471,
                {"provides": frozenset()}),
    PartMapping("EquiTriangle1p5", MiscEquipment, "SP-T18 Structural Panel", 1472,
                {"provides": frozenset()}),
    PartMapping("EquiTriangle2", MiscEquipment, "SP-T25 Structural Panel", 1473,
                {"provides": frozenset()}),
    PartMapping("Panel0", MiscEquipment, "SP-S06 Structural Panel", 1474,
                {"provides": frozenset()}),
    PartMapping("Panel1", MiscEquipment, "SP-S12 Structural Panel", 1475,
                {"provides": frozenset()}),
    PartMapping("Panel1p5", MiscEquipment, "SP-S18 Structural Panel", 1476,
                {"provides": frozenset()}),
    PartMapping("Panel2", MiscEquipment, "SP-S25 Structural Panel", 1477,
                {"provides": frozenset()}),
    PartMapping("Triangle0", MiscEquipment, "SP-R06 Structural Panel", 1478,
                {"provides": frozenset()}),
    PartMapping("Triangle1", MiscEquipment, "SP-R12 Structural Panel", 1479,
                {"provides": frozenset()}),
    PartMapping("Triangle1p5", MiscEquipment, "SP-R18 Structural Panel", 1480,
                {"provides": frozenset()}),
    PartMapping("Triangle2", MiscEquipment, "SP-R25 Structural Panel", 1481,
                {"provides": frozenset()}),
    PartMapping("Tube1", MiscEquipment, "T-12 Structural Tube", 1482,
                {"provides": frozenset()}),
    PartMapping("Tube1p5", MiscEquipment, "T-18 Structural Tube", 1483,
                {"provides": frozenset()}),
    PartMapping("Tube2", MiscEquipment, "T-25 Structural Tube", 1484,
                {"provides": frozenset()}),
    PartMapping("Tube3", MiscEquipment, "T-37 Structural Tube", 1485,
                {"provides": frozenset()}),
    PartMapping("Tube4", MiscEquipment, "T-50 Structural Tube", 1486,
                {"provides": frozenset()}),
]


# ---------------------------------------------------------------------------
# Builder helpers
# ---------------------------------------------------------------------------

# Propellants a tank cannot drain to become compatible with an engine that
# doesn't consume them. MonoPropellant is RCS fuel — distinct supply chain,
# not interchangeable with main propellant feed.
UNDRAINABLE_PROPELLANTS: frozenset[str] = frozenset({"MonoPropellant"})


def usable_fuel_mass(
    tank: "FuelTank", engine_propellants: frozenset[str]
) -> float:
    """Return tonnes of usable propellant for an engine that consumes the
    given propellant set, or 0.0 if the tank cannot fuel the engine.

    All propellants the engine needs must be present in the tank with
    positive mass. Propellants the tank carries that the engine does not
    need are drained (0% fill), except those in UNDRAINABLE_PROPELLANTS.
    """
    tank_resources = dict(tank.fuel_masses)
    have = frozenset(tank_resources)
    if not engine_propellants <= have:
        return 0.0
    if (have - engine_propellants) & UNDRAINABLE_PROPELLANTS:
        return 0.0
    return sum(tank_resources[p] for p in engine_propellants)


def _fuel_type_from_propellants(propellants: dict[str, float]) -> str:
    """Derive fuel_type from an engine's propellant dict."""
    keys = set(propellants.keys()) - {"ElectricCharge"}
    if keys == {"LiquidFuel", "Oxidizer"}:
        return "lfo"
    if keys == {"LiquidFuel"}:
        return "lf"
    if "XenonGas" in keys:
        return "xenon"
    if keys == {"MonoPropellant"}:
        return "monoprop"
    raise ValueError(f"Unknown propellant combination: {propellants}")


def _fuel_type_from_resources(resources: dict[str, float]) -> str:
    """Derive fuel_type from a tank's resource dict."""
    keys = set(resources.keys()) - {"ElectricCharge"}
    if "LiquidFuel" in keys and "Oxidizer" in keys:
        return "lfo"
    if keys == {"LiquidFuel"}:
        return "lf"
    if "XenonGas" in keys:
        return "xenon"
    if "MonoPropellant" in keys:
        return "monoprop"
    raise ValueError(f"Unknown resource combination: {resources}")


def _best_size_class(profiles: list[str]) -> float:
    """Pick the largest non-srf bulkhead diameter."""
    best = 0.0
    for p in profiles:
        if p == "srf":
            continue
        d = _BULKHEAD_DIAMETER.get(p, 0.0)
        if d > best:
            best = d
    # srf-only parts (radial mounts) default to smallest size
    return best if best > 0.0 else 0.625


def _fuel_mass_from_resources(resources: dict[str, float]) -> float:
    """Compute total fuel mass (tonnes) from a resource dict."""
    total = 0.0
    for name, amount in resources.items():
        if name == "ElectricCharge":
            continue
        density = _RESOURCE_DENSITY.get(name)
        if density is None:
            continue
        total += amount * density
    return total


def _build_part(part_type: type, cfg: dict, overrides: dict, name: str) -> AnyPart:
    """Construct a frozen part dataclass from cfg JSON data + manual overrides."""
    cfg_name = name
    mass = cfg["mass"]
    size = _best_size_class(cfg.get("bulkhead_profiles", []))

    bulkheads = cfg.get("bulkhead_profiles", [])
    is_radial = "srf" in bulkheads

    if part_type is Engine:
        eng = cfg["engine"]
        isp_vac = eng["isp_vac"]
        isp_atm = eng["isp_atm"]
        vac_thrust = eng["max_thrust"]
        atm_thrust = vac_thrust * (isp_atm / isp_vac) if isp_vac > 0 else 0.0
        propellants = tuple(sorted(
            p for p in eng["propellants"].keys() if p != "ElectricCharge"
        ))
        return Engine(
            name=cfg_name,
            vac_isp=isp_vac,
            atm_isp=isp_atm,
            vac_thrust=vac_thrust,
            atm_thrust=atm_thrust,
            mass=mass,
            throttleable=not eng.get("throttle_locked", False),
            has_gimbal=cfg.get("has_gimbal", False),
            size_class=size,
            fuel_type=_fuel_type_from_propellants(eng["propellants"]),
            radial_mountable=is_radial,
            propellants=propellants,
        )

    if part_type is FuelTank:
        resources = cfg.get("resources", {})
        fuel_masses = tuple(sorted(
            (name, amount * _RESOURCE_DENSITY[name])
            for name, amount in resources.items()
            if name != "ElectricCharge" and name in _RESOURCE_DENSITY
        ))
        return FuelTank(
            name=cfg_name,
            dry_mass=mass,
            fuel_mass=_fuel_mass_from_resources(resources),
            fuel_type=_fuel_type_from_resources(resources),
            size_class=size,
            max_count=overrides.get("max_count", 0),
            fuel_masses=fuel_masses,
        )

    if part_type is SolidBooster:
        eng = cfg["engine"]
        resources = cfg.get("resources", {})
        isp_vac = eng["isp_vac"]
        isp_atm = eng["isp_atm"]
        vac_thrust = eng["max_thrust"]
        atm_thrust = vac_thrust * (isp_atm / isp_vac) if isp_vac > 0 else 0.0
        return SolidBooster(
            name=cfg_name,
            vac_isp=isp_vac,
            atm_isp=isp_atm,
            vac_thrust=vac_thrust,
            atm_thrust=atm_thrust,
            dry_mass=mass,
            fuel_mass=_fuel_mass_from_resources(resources),
            has_gimbal=cfg.get("has_gimbal", False),
            size_class=size,
            radial_mountable=is_radial,
        )

    if part_type is HeatShield:
        return HeatShield(name=cfg_name, mass=mass, size_class=size)

    if part_type is Parachute:
        chute = cfg.get("parachute", {})
        return Parachute(
            name=cfg_name,
            mass=mass,
            drag_area=chute.get("fully_deployed_drag", 0.0),
            is_drogue=overrides.get("is_drogue", False),
            is_radial=overrides.get("is_radial", False),
        )

    if part_type is LandingLeg:
        return LandingLeg(
            name=cfg_name,
            mass=mass,
            tier=overrides["tier"],
        )

    if part_type is Decoupler:
        kind = ("radial" if cfg.get("has_module_anchored_decouple")
                else "stack")
        return Decoupler(name=cfg_name, mass=mass, kind=kind, size_class=size)

    if part_type is MiscEquipment:
        return MiscEquipment(
            name=cfg_name,
            mass=mass,
            provides=overrides.get("provides", frozenset()),
        )

    raise TypeError(f"Unknown part type: {part_type}")


# ---------------------------------------------------------------------------
# Loader: reads data/parts.json and builds PART_DB at import time
# ---------------------------------------------------------------------------

# Items that are registered as one type but also provide a secondary role.
# Each entry adds a MiscEquipment with the given provides to the same item.
_DUAL_PURPOSE: dict[str, frozenset[str]] = {
    "Size4_EngineAdapter_01": frozenset({"multi_mount"}),
    "mk2_1m_Bicoupler": frozenset({"multi_mount"}),
}


def _load_part_db() -> dict[str, list[AnyPart]]:
    raw = pkgutil.get_data("worlds.ksp1", "data/parts.json")
    assert raw is not None, "data/parts.json not found in package"
    all_parts: dict = json.loads(raw.decode("utf-8"))

    db: dict[str, list[AnyPart]] = {}
    for mapping in PART_REGISTRY:
        cfg = all_parts.get(mapping.cfg_name)
        if cfg is None:
            raise ValueError(
                f"PART_REGISTRY references cfg name {mapping.cfg_name!r} "
                f"which does not exist in parts.json"
            )
        part = _build_part(mapping.part_type, cfg, mapping.overrides,
                           name=mapping.ksp_name)
        db.setdefault(mapping.ksp_name, []).append(part)

        # Dual-purpose parts: also add a MiscEquipment to the same item
        provides = _DUAL_PURPOSE.get(mapping.cfg_name)
        if provides is not None:
            db[mapping.ksp_name].append(
                MiscEquipment(name=mapping.ksp_name, mass=cfg["mass"],
                              provides=provides)
            )
    return db


PART_DB: dict[str, list[AnyPart]] = _load_part_db()


# ---------------------------------------------------------------------------
# Progressive part tier definitions
# ---------------------------------------------------------------------------
# Maps progressive item name → {tier: [ksp_names]}
# Tier numbers are 1-based; receiving N copies unlocks tiers 1..N.

PROGRESSIVE_PART_TIERS: dict[str, dict[int, list[str]]] = {
    # --- Launch Engines (atmosphere-capable, by thrust class) ---
    "Progressive Launch Engine": {
        1: [
            "liquidEngine.v2",           # LV-T30 Reliant (240kN)
            "liquidEngine2.v2",          # LV-T45 Swivel (215kN)
            "LiquidEngineRV-1",          # RV-1 Cub (32kN, MH)
            "toroidalAerospike",         # T-1 Dart (180kN, 290s atm Isp; 0.625m stack)
        ],
        2: [
            # Mainstream stack ascent engines only — radial engines split
            # into Progressive Radial Engine to avoid weak rep selection.
            "engineLargeSkipper.v2",     # RE-I5 Skipper (650kN)
            "LiquidEngineLV-TX87",       # LV-TX87 Bobcat (400kN, MH)
            "LiquidEngineRK-7",          # RK-7 Kodiak (260kN, MH)
            "LiquidEngineRE-I2",         # RE-I2 Skiff (300kN, MH)
        ],
        3: [
            "liquidEngineMainsail.v2",   # RE-M3 Mainsail (1500kN)
            "Size2LFB.v2",              # LFB KR-1x2 Twin-Boar (2000kN)
            "SSME",                      # S3 KS-25 Vector (1000kN)
            "LiquidEngineKE-1",          # KE-1 Mastodon (1350kN, MH)
            "Size3EngineCluster",        # S3 KS-25x4 Mammoth (4000kN)
        ],
    },
    # --- Vacuum Engines (high-ISP transfer + specialty fuel) ---
    "Progressive Vacuum Engine": {
        1: [
            # Stack vacuum engines only — Spider (radial) split into
            # Progressive Radial Engine for power-level homogeneity.
            "liquidEngine3.v2",          # LV-909 Terrier (60kN, 345s vac)
            "liquidEngineMini.v2",       # 48-7S Spark (20kN, 320s vac)
            "microEngine.v2",            # LV-1 Ant (2kN, 315s vac)
        ],
        2: [
            "liquidEngine2-2.v2",        # RE-L10 Poodle (250kN, 350s vac)
            "LiquidEngineLV-T91",        # LV-T91 Cheetah (125kN, 355s vac, MH)
            "LiquidEngineRE-J10",        # RE-J10 Wolfhound (375kN, 380s vac, MH)
        ],
        3: [
            # Heavy LFO vacuum workhorse. Single candidate so the rep is
            # deterministic. Rhino has poor atmospheric ISP (205s) which made
            # it a 15% killer rep when it lived in Launch Engine tier 3; here
            # it's used for its actual role (heavy upper-stage / interplanetary).
            "Size3AdvancedEngine",       # KR-2L+ Rhino (2000kN, 340s vac, 9t)
        ],
        4: [
            # Advanced specialty propulsion — both require specific fuel types
            # (Nerv = LF-only tanks, Ion = xenon) and have niche thrust profiles.
            # Bumped one tier above the LFO workhorse so they read as a deeper
            # progression unlock.
            "nuclearEngine",             # LV-N Nerv (60kN, 800s vac, uses LF)
            "ionEngine",                 # IX-6315 Dawn (2kN, 4200s vac, uses xenon)
        ],
    },
    # --- Radial Engines (asparagus boosters / specialty radial-mount) ---
    # Split out from Progressive Launch/Vacuum Engine to keep those tiers
    # mainstream-engine-only. Radial engines have wildly different power
    # levels from stack ascent engines and can land as weak reps otherwise.
    "Progressive Radial Engine": {
        1: [  # Small radials
            "smallRadialEngine.v2",      # 24-77 Twitch (16kN)
            "radialEngineMini.v2",       # LV-1R Spider (2kN vac)
        ],
        2: [  # Mid radial
            "radialLiquidEngine1-2",     # Mk-55 Thud (120kN)
        ],
    },
    # --- Solid Rocket Boosters (by thrust/total impulse class) ---
    "Progressive SRB": {
        1: [
            "Mite",                      # FM1 Mite (12kN)
            "Shrimp",                    # F3S0 Shrimp (30kN)
            "solidBooster.sm.v2",        # RT-5 Flea (192kN)
        ],
        2: [
            "solidBooster.v2",           # RT-10 Hammer (227kN)
            "solidBooster1-1",           # BACC Thumper (300kN)
            "Pollux",                    # THK Pollux (1300kN, MH)
        ],
        3: [
            "MassiveBooster",            # S1 SRB-KD25k Kickback (670kN)
            "Thoroughbred",              # S2-17 Thoroughbred (1700kN)
            "Clydesdale",                # S2-33 Clydesdale (3300kN)
        ],
    },
    # --- LFO Tanks (by fuel mass, not size class) ---
    "Progressive LFO Tank": {
        1: [  # Tiny (< 1.0t fuel)
            "miniFuelTank",              # Oscar-B (0.2t)
            "fuelTankSmallFlat",         # FL-T100 (0.5t)
        ],
        2: [  # Small (1.0 - 4.5t fuel)
            "fuelTankSmall",             # FL-T200 (1.0t)
            "Size1p5.Tank.01",           # FL-TX220 (1.1t, MH)
            "fuelTank",                  # FL-T400 (2.0t)
            "Size1p5.Tank.02",           # FL-TX440 (2.2t, MH)
            "fuelTank.long",             # FL-T800 (4.0t)
            "Rockomax8BW",              # X200-8 (4.0t)
            "Size1p5.Tank.03",           # FL-TX900 (4.5t, MH)
        ],
        3: [  # Medium (5.0 - 32.0t fuel)
            "Size1p5.Tank.05",           # FL-C1000 (6.03t, MH)
            "Size1p5.Size2.Adapter.01",  # FL-A215 (6.0t, MH)
            "Rockomax16.BW",            # X200-16 (8.0t)
            "Size1p5.Tank.04",           # FL-TX1800 (9.0t, MH)
            "Rockomax32.BW",            # X200-32 (16.0t)
            "Size3SmallTank",            # S3-3600 (18.0t)
            # Rockomax64.BW (Jumbo-64, 32t) sits at the top of T3 by
            # size_class (2.5m).  Demoted from T4 because rep-analysis
            # showed it as the universal underperformer there (78-89%
            # Jool-moon feasibility vs 100% for all size-3+ T4 tanks).
            "Rockomax64.BW",            # Jumbo-64 (32.0t)
        ],
        4: [  # Large (>= 32.0t fuel, size_class 3+)
            "Size3MediumTank",           # S3-7200 (36.0t)
            "Size3LargeTank",            # S3-14400 (72.0t)
            "Size3.Size4.Adapter.01",    # S3-S4 Adapter (32.0t, MH)
            "Size4.Tank.01",             # S4-64 (32.0t, MH)
            "Size4.Tank.02",             # S4-128 (64.0t, MH)
            "Size4.Tank.03",             # S4-256 (128.0t, MH)
            "Size4.Tank.04",             # S4-512 (256.0t, MH)
        ],
    },
    # --- Heat Shields (by size class) ---
    "Progressive Heat Shield": {
        1: [
            "HeatShield0",              # 0.625m
            "HeatShield1",              # 1.25m
            "HeatShield1p5",            # 1.875m (MH)
        ],
        2: [
            "HeatShield2",              # 2.5m
            "HeatShield3",              # 3.75m
            "InflatableHeatShield",      # 10m inflatable
        ],
    },
    # --- Stack Decouplers (serial staging) ---
    # Docking ports are folded in at tier+1 of their natural size — guarantees
    # the player always has a non-docking-port separator at their current tier.
    "Progressive Stack Decoupler": {
        1: [  # Small/medium decouplers — no docking ports here.
            "Decoupler.0",              # TD-06
            "Decoupler.1",              # TD-12
            "Decoupler.1p5",            # TD-18 (MH)
            "Separator.0",              # TS-06
            "Separator.1",              # TS-12
            "Separator.1p5",            # TS-18 (MH)
            "Size1p5.Strut.Decoupler",  # Size 1.5 Decoupler (MH)
        ],
        2: [  # Large decouplers + size 0/1 docking ports (natural tier 1, bumped here).
            "Decoupler.2",              # TD-25
            "Decoupler.3",              # TD-37
            "Decoupler.4",              # TD-50 (MH)
            "Separator.2",              # TS-25
            "Separator.3",              # TS-37
            "Separator.4",              # TS-50 (MH)
            "dockingPort1",              # Clamp-O-Tron Shielded (size1)
            "dockingPort2",              # Clamp-O-Tron (size1)
            "dockingPort3",              # Clamp-O-Tron Jr. (size0)
            "mk2DockingPort",            # Mk2 Clamp-O-Tron (size1+mk2)
        ],
        3: [  # Size 2+ docking ports (natural tier 2, bumped here).
            "dockingPortLarge",          # Clamp-O-Tron Sr. (size2)
        ],
    },
    # --- Radial Decouplers (parallel/asparagus staging) ---
    # Tier 3 = fuelLine: gates asparagus staging behind 3 progressive copies.
    "Progressive Radial Decoupler": {
        1: [
            "radialDecoupler",           # TT-38K
            "radialDecoupler1-2",        # Hydraulic Detachment Manifold
        ],
        2: [
            "radialDecoupler2",          # TT-70
        ],
        3: [
            "fuelLine",                  # FTX-2 External Fuel Duct
        ],
    },
    # --- Multi-mount adapters: 2-way -> 3/4-way -> Engine Plates ---
    # Tri/quad couplers are notably better than bi; engine plates are the best.
    "Progressive Engine Plate": {
        1: [  # 2-way couplers/adapters (basic)
            "stackBiCoupler.v2",         # TVR-200 Stack Bi-Coupler
            "adapterLargeSmallBi",        # Rockomax Brand Adapter (bi)
            "mk2.1m.Bicoupler",          # Mk2 Bicoupler
        ],
        2: [  # 3-way / 4-way couplers/adapters
            "stackTriCoupler.v2",        # TVR-300 Stack Tri-Coupler
            "stackQuadCoupler",           # TVR-400L Stack Quad-Coupler
            "adapterLargeSmallTri",       # Rockomax Brand Adapter (tri)
            "adapterLargeSmallQuad",      # Rockomax Brand Adapter (quad)
        ],
        3: [  # Small Engine Plates (0.625m / 1.25m output)
            "EnginePlate5",              # EP-12
            "EnginePlate1p5",            # EP-18
            "EnginePlate2",              # EP-25
        ],
        4: [  # Medium Engine Plates (1.875m / 2.5m output)
            "EnginePlate3",              # EP-37
            "EnginePlate4",              # EP-50
        ],
        5: [  # Large (3.75m output stack)
            "Size4.EngineAdapter.01",    # Kerbodyne Engine Cluster Adapter
        ],
    },
    # --- Parachutes (basic stack chutes -> radial) ---
    "Progressive Parachute": {
        1: [  # Basic stack chutes
            "parachuteSingle",           # Mk16 Parachute
            "parachuteLarge",            # Mk25 Parachute
        ],
        2: [  # Radial chutes (for spaceplanes / spacecraft)
            "parachuteRadial",           # Mk2-R Radial-Mount Parachute
        ],
    },
    # --- Ladders (basic telescopic -> housed bay) ---
    "Progressive Ladder": {
        1: [
            "telescopicLadder",          # Telescopic Ladder
        ],
        2: [
            "telescopicLadderBay",       # Telescopic Ladder Bay
        ],
    },
    # --- Landing Legs (heavy first, then variety in lighter options) ---
    "Progressive Landing Leg": {
        1: [
            "landingLeg1-2",             # LT-2 Landing Strut (heavy)
        ],
        2: [
            "landingLeg1",               # LT-1 Landing Struts
            "miniLandingLeg",            # LT-05 Micro Landing Strut
        ],
    },
    # --- Science Instruments (basic -> advanced) ---
    # Note: sensorThermometer is precollected; not in this group.
    "Progressive Science Instrument": {
        1: [  # Basic atmospheric/biomes science
            "GooExperiment",             # Mystery Goo Containment Unit
            "sensorBarometer",           # PresMat Barometer
        ],
        2: [  # Mid-tier
            "science.module",            # SC-9001 Science Jr.
            "sensorAtmosphere",          # Atmospheric Fluid Spectro-Variometer
        ],
        3: [  # Advanced specialized sensors
            "sensorAccelerometer",       # Double-C Seismic Accelerometer
            "sensorGravimeter",          # GRAVMAX Negative Gravioli Detector
        ],
    },
    # --- Capsules (crewed command pods) ---
    "Progressive Capsule": {
        1: [  # Basic: 1-crew sealed pods (External Command Seat moved to
              # useful — it's an open seat, not a real capsule).
            "mk1pod.v2",                # Mk1 Command Pod
            "kv1Pod",                    # KV-1 (MH)
        ],
        2: [  # Landers, 2-crew, planes
            "landerCabinSmall",          # Mk1 Lander Can
            "kv2Pod",                    # KV-2 (MH)
            "Mk2Pod",                   # Mk2 Command Pod (MH)
            "MEMLander",                 # M.E.M. (MH)
            "MK1CrewCabin",             # Mk1 Crew Cabin
            "Mark1Cockpit",              # Mk1 Cockpit
            "Mark2Cockpit",              # Mk1 Inline Cockpit
            "cupola",                    # Cupola
        ],
        3: [  # Heavy/3+ crew, stations, spaceplanes
            "mk1-3pod",                 # Mk1-3 Command Pod
            "mk2LanderCabin.v2",        # Mk2 Lander Can
            "kv3Pod",                    # KV-3 (MH)
            "mk2Cockpit.Standard",       # Mk2 Cockpit
            "mk2Cockpit.Inline",         # Mk2 Inline Cockpit
            "mk2CrewCabin",              # Mk2 Crew Cabin
            "mk3Cockpit.Shuttle",        # Mk3 Cockpit
            "mk3CrewCabin",              # Mk3 Passenger Module
            "crewCabin",                 # Hitchhiker
            "Large.Crewed.Lab",          # Mobile Processing Lab
        ],
    },
    # --- Probe Cores (by SAS level) ---
    "Progressive Probe Core": {
        1: [  # SAS 0-1, no reaction wheel
            "probeCoreSphere.v2",        # Stayputnik (SAS 0)
            "probeCoreOcto.v2",          # OKTO (SAS 1)
            "probeCoreOcto2.v2",         # OKTO2 (SAS 1)
            "probeCoreCube",             # QBE (SAS 1)
            "roverBody.v2",              # RoveMate (SAS 1)
        ],
        2: [  # SAS 2+
            "probeCoreHex.v2",           # HECS (SAS 2, has reaction_wheel)
            "probeStackSmall",           # RC-001S (SAS 2, has reaction_wheel)
            "MpoProbe",                  # MPO Probe (MH)
            "MtmStage",                  # MTM Stage (MH)
        ],
        3: [  # SAS 3, all have reaction_wheel
            "HECS2.ProbeCore",           # HECS2 (SAS 3)
            "probeStackLarge",           # RC-L01 (SAS 3)
            "mk2DroneCore",              # Mk2 Drone Core (SAS 3)
        ],
    },
    # --- Solar Panels (fixed < retractable < giant) ---
    "Progressive Solar Panel": {
        1: [  # Fixed panels
            "solarPanels5",              # OX-STAT
            "LgRadialSolarPanel",        # OX-STAT-XL
            "solarPanelOX10C",           # OX-10C
            "solarPanelSP10C",           # SP-10C
        ],
        2: [  # Retractable panels
            "solarPanels3",              # OX-4W
            "solarPanels4",              # OX-4L
            "solarPanels1",              # SP-W
            "solarPanels2",              # SP-L
            "solarPanelOX10L",           # OX-10L
            "solarPanelSP10L",           # SP-10L
        ],
        3: [  # Giant array
            "largeSolarPanel",           # Gigantor XL Solar Array
        ],
    },
    # --- Relay Antennas (by comm range) ---
    "Progressive Relay": {
        1: [
            "longAntenna",               # Communotron 16
            "SurfAntenna",               # Communotron 16-S
            "HighGainAntenna5.v2",       # HG-5
        ],
        2: [
            "RelayAntenna5",             # RA-2
            "mediumDishAntenna",          # Communotron DTS-M1
        ],
        3: [
            "HighGainAntenna",           # Communotron HG-55
            "RelayAntenna50",            # RA-15
        ],
        4: [
            "commDish",                  # Communotron 88-88
            "RelayAntenna100",           # RA-100
        ],
    },
    # --- SAS / Reaction Wheels (attitude control) ---
    # Standalone reaction-wheel modules.  Each tier provides reaction wheels
    # at increasing torque/mass.  Bumping this chain is the cheap fix for
    # ``no_attitude_control`` blockers when probe-core/capsule reaction
    # wheels are absent or insufficient.
    "Progressive SAS": {
        1: [
            "sasModule",                 # Stock SAS Module (0.05t)
        ],
        2: [
            "advSasModule",              # Advanced Inline Stabilizer (0.1t)
        ],
        3: [
            "asasmodule1-2",             # Large Reaction Wheel Module (0.2t)
        ],
    },
    # --- Xenon Tanks ---
    # Three stock xenon containers — all tiny. Single tier; any copy unlocks
    # the rep, granting xenon fuel storage so an ion-engine vacuum-engine
    # rep is actually usable.
    "Progressive Xenon Tank": {
        1: [
            "xenonTankRadial",           # PB-X50R (0.04t fuel, 0.625m radial)
            "xenonTank",                 # PB-X150 (0.07t fuel, 0.625m)
            "xenonTankLarge",            # PB-X750 (0.57t fuel, 1.25m)
        ],
    },
}

# Max tier count per progressive item (number of copies in the AP pool)
PROGRESSIVE_PART_COUNTS: dict[str, int] = {
    name: max(tiers.keys()) for name, tiers in PROGRESSIVE_PART_TIERS.items()
}

# All ksp_names that belong to progressive chains. During generation, one per
# tier is selected as the representative (removed from pool); the rest stay
# as gated useful items. This set is used to identify absorbed parts.
PROGRESSIVE_PART_NAMES: frozenset[str] = frozenset(
    ksp_name
    for tiers in PROGRESSIVE_PART_TIERS.values()
    for tier_parts in tiers.values()
    for ksp_name in tier_parts
)

# Validation: no part in multiple progressive categories
def _validate_progressive_tiers() -> None:
    seen: dict[str, str] = {}  # ksp_name → category
    for category, tiers in PROGRESSIVE_PART_TIERS.items():
        for tier, names in tiers.items():
            for name in names:
                if name in seen:
                    raise ValueError(
                        f"Part {name!r} in both {seen[name]!r} and {category!r}"
                    )
                seen[name] = category
                if name not in PART_DB:
                    raise ValueError(
                        f"Progressive tier part {name!r} ({category} T{tier}) "
                        f"not found in PART_DB"
                    )

_validate_progressive_tiers()
